import {OfflineDB} from './offline.js';
import {Session} from './api.js';
import {autoScoutListingHealth,normalizeAutoScoutUrl} from './autoscout-link.js?v=1.6.3';

const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
let vehicles=[];let scheduled=false;
function dealerId(){return Session.get()?.dealer?.id||null}
function label(code){return ({INVALID_URL:'link non valido',MISSING_URL:'manca link',MISSING_LISTING_ID:'manca ID annuncio',MISSING_PUBLISHED_AT:'manca data online',MISSING_PRICE:'manca prezzo',ERROR_WITHOUT_NOTE:'errore senza nota',STALE_30:'online da 30+ giorni',STALE_60:'online da 60+ giorni'})[code]||code}

async function load(){const id=dealerId();vehicles=id?await OfflineDB.list('vehicles',id):[];enhance()}
function injectStyle(){if($('#autoscoutSafetyStyle'))return;const s=document.createElement('style');s.id='autoscoutSafetyStyle';s.textContent=`.as-health{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:0 0 12px}.as-health>div{background:#fff;border:1px solid var(--line);border-radius:14px;padding:11px}.as-health span{display:block;font-size:7px;font-weight:900;color:var(--muted)}.as-health b{display:block;font-size:15px;margin-top:4px}.as-health-note{grid-column:1/-1!important;background:#fffaf0!important}.as-live-link{display:inline-grid;place-items:center;text-decoration:none!important}.as-link-warning{margin:8px 0 0;padding:9px 10px;border-radius:10px;background:#fff3e3;color:#7b4c0e;font-size:8px;line-height:1.45}.as-link-ok{background:#edf6f1;color:#176442}.as-row-actions{display:flex;gap:6px;flex-wrap:wrap}.as-row-actions>*{flex:1 1 auto}@media(max-width:900px){.as-health{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function vehicleForRow(row){const id=row.querySelector('[data-as-open]')?.dataset.asOpen;return vehicles.find(v=>v.id===id)||null}
function renderHealth(){const root=$('#autoscoutApp');if(!root)return;const active=vehicles.filter(v=>!v.deleted_at&&!['VENDUTA','DA_CONSEGNARE','CONSEGNATA'].includes(v.status));const health=active.map(v=>autoScoutListingHealth(v));const published=health.filter(h=>h.status==='PUBLISHED').length,verified=health.filter(h=>h.verified).length,broken=health.filter(h=>h.blocking.length).length,stale=health.filter(h=>h.warnings.includes('STALE_30')||h.warnings.includes('STALE_60')).length;let panel=$('#autoscoutHealth');if(!panel){panel=document.createElement('div');panel.id='autoscoutHealth';panel.className='as-health';const section=root.querySelector('.section');section?section.after(panel):root.prepend(panel)}panel.innerHTML=`<div><span>ONLINE</span><b>${published}</b></div><div><span>VERIFICATI</span><b>${verified}</b></div><div><span>DA COMPLETARE</span><b>${broken}</b></div><div><span>30+ GIORNI ONLINE</span><b>${stale}</b></div>${broken?'<div class="as-health-note"><span>CONTROLLO QUALITÀ</span><b style="font-size:9px">Gli annunci segnati ONLINE devono avere link AutoScout24 valido, ID annuncio, data online e prezzo.</b></div>':''}`}
function enhanceRows(){for(const row of $$('.as-row')){const vehicle=vehicleForRow(row);if(!vehicle)continue;const h=autoScoutListingHealth(vehicle),button=row.querySelector('[data-as-open]');if(!button)continue;let wrap=button.parentElement?.classList.contains('as-row-actions')?button.parentElement:null;if(!wrap){wrap=document.createElement('div');wrap.className='as-row-actions';button.replaceWith(wrap);wrap.appendChild(button)}wrap.querySelector('[data-as-live]')?.remove();if(h.url){const a=document.createElement('a');a.dataset.asLive='1';a.className='as-secondary as-live-link';a.href=h.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Apri AutoScout ↗';wrap.appendChild(a)}}}
function enhanceDrawer(){const form=$('#asManage');if(!form)return;const input=form.elements.autoscout_url,status=form.elements.autoscout_status,listing=form.elements.autoscout_listing_id,published=form.elements.autoscout_published_at;if(!input)return;let note=$('#asLinkQuality');if(!note){note=document.createElement('div');note.id='asLinkQuality';note.className='as-link-warning wide';form.insertBefore(note,form.lastElementChild)}const candidate={autoscout_url:input.value,autoscout_status:status?.value,autoscout_listing_id:listing?.value,autoscout_published_at:published?.value,autoscout_price:form.elements.autoscout_price?.value};const h=autoScoutListingHealth(candidate);note.classList.toggle('as-link-ok',h.blocking.length===0);note.textContent=h.blocking.length?`Da sistemare: ${h.blocking.map(label).join(', ')}.`:(h.url?'Collegamento AutoScout24 verificato.':'Compila il collegamento quando l’annuncio viene pubblicato.');let live=$('#asDrawerLive');if(live)live.remove();if(h.url){live=document.createElement('a');live.id='asDrawerLive';live.className='as-copy-btn as-live-link';live.href=h.url;live.target='_blank';live.rel='noopener noreferrer';live.textContent='Apri annuncio AutoScout24 ↗';form.closest('.as-sheet-body')?.insertBefore(live,form.closest('details')||null)}}
function enhance(){if(typeof document==='undefined')return;injectStyle();renderHealth();enhanceRows();enhanceDrawer()}
function schedule(){if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;enhance()},30)}

if(typeof document!=='undefined'){
  document.addEventListener('submit',e=>{const form=e.target;if(form?.id!=='asManage')return;const fd=new FormData(form),status=String(fd.get('autoscout_status')||''),raw=String(fd.get('autoscout_url')||'').trim(),url=normalizeAutoScoutUrl(raw);if(raw&&!url){e.preventDefault();e.stopImmediatePropagation();alert('Il link deve essere un URL HTTPS reale di AutoScout24.');return}if(status==='PUBLISHED'){const h=autoScoutListingHealth({autoscout_status:status,autoscout_url:raw,autoscout_listing_id:fd.get('autoscout_listing_id'),autoscout_published_at:fd.get('autoscout_published_at'),autoscout_price:fd.get('autoscout_price')});if(h.blocking.length){e.preventDefault();e.stopImmediatePropagation();alert(`Annuncio ONLINE incompleto: ${h.blocking.map(label).join(', ')}.`)}}},true);
  document.addEventListener('input',e=>{if(e.target?.closest?.('#asManage'))enhanceDrawer()});
  document.addEventListener('change',e=>{if(e.target?.closest?.('#asManage'))enhanceDrawer()});
  const observer=new MutationObserver(schedule);observer.observe(document.documentElement,{subtree:true,childList:true});
  window.addEventListener('dealer:session',()=>load().catch(()=>{}));window.addEventListener('dealer:queue-changed',()=>load().catch(()=>{}));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>load().catch(()=>{}));else load().catch(()=>{});
}
