import {OfflineDB} from './offline.js';
import {Session} from './api.js';
import {BACKUP_SIGNATURE,BACKUP_STORES,BACKUP_VERSION,backupSummary,mergeForRestore,validateBackup} from './backup-core.js?v=1.6.1';

const $=(selector,root=document)=>root.querySelector(selector);const cfg=()=>window.DEALER_CONFIG||{};
const state={pending:null,plan:null,busy:false,message:'',tone:'ok'};
function dealerId(){return Session.get()?.dealer?.id||'demo-malu23'}
function canBackup(){const p=Session.get()?.profile||{};return p.role==='ADMIN'||p.permissions?.admin_manage===true||cfg().demoMode}
function formatDate(value){return value?new Intl.DateTimeFormat('it-IT',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'mai'}
function safeName(value){return String(value||'malu23').toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'')||'malu23'}
function readAsDataUrl(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})}
async function portableRow(name,row){if(name!=='document_blobs'||!row?.blob)return row;const dataUrl=await readAsDataUrl(row.blob);const {blob,...rest}=row;return {...rest,blob_data_url:dataUrl,blob_type:blob.type||'application/octet-stream',blob_name:blob.name||null}}
function restoreBlob(row){if(!row?.blob_data_url)return row;const [header,data='']=String(row.blob_data_url).split(',',2),mime=/data:([^;]+)/.exec(header)?.[1]||row.blob_type||'application/octet-stream',binary=atob(data),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const blob=row.blob_name?new File([bytes],row.blob_name,{type:mime}):new Blob([bytes],{type:mime});const {blob_data_url,blob_type,blob_name,...rest}=row;return {...rest,blob}}

async function createBackup(){
  state.busy=true;state.message='Raccolgo i dati della concessionaria…';render();try{
    const stores={};for(const name of BACKUP_STORES){const rows=await OfflineDB.list(name,dealerId());stores[name]=await Promise.all(rows.map(row=>portableRow(name,row)))}
    const now=new Date().toISOString(),payload={signature:BACKUP_SIGNATURE,version:BACKUP_VERSION,app_version:cfg().version||'1.6.1',dealer_id:dealerId(),dealer_slug:Session.get()?.dealer?.slug||'malu23',created_at:now,stores},json=JSON.stringify(payload),blob=new Blob([json],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${safeName(payload.dealer_slug)}-backup-${now.slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1500);await OfflineDB.setMeta(`backup:last:${dealerId()}`,now);state.message=`Backup pronto · ${backupSummary(validateBackup(payload,dealerId()))}`;state.tone='ok';
  }catch(err){state.message=errorLabel(err.message);state.tone='bad'}finally{state.busy=false;render()}
}

async function chooseBackup(file){
  state.pending=null;state.plan=null;if(!file)return;if(file.size>128*1024*1024){state.message='Il file supera 128 MB.';state.tone='bad';render();return}
  state.busy=true;state.message='Controllo il backup…';render();try{const payload=JSON.parse(await file.text()),plan=validateBackup(payload,dealerId());state.pending=payload;state.plan=plan;state.message=`Backup del ${formatDate(plan.createdAt)} · ${backupSummary(plan)}`;state.tone='ok'}catch(err){state.message=errorLabel(err.message);state.tone='bad'}finally{state.busy=false;render()}
}

async function restoreBackup(){
  if(!state.pending||!state.plan)return;state.busy=true;state.message='Ripristino sicuro in corso…';render();let restored=0,keptNewer=0;
  try{for(const name of BACKUP_STORES){const current=await OfflineDB.list(name,dealerId()),incoming=(state.pending.stores[name]||[]).map(row=>restoreBlob(row)),merged=mergeForRestore(current,incoming);if(merged.rows.length)await OfflineDB.bulkPut(name,merged.rows);restored+=merged.restored;keptNewer+=merged.keptNewer}await OfflineDB.setMeta(`backup:restore:${dealerId()}`,new Date().toISOString());state.pending=null;state.plan=null;state.message=`Ripristino completato: ${restored} elementi aggiornati${keptNewer?`, ${keptNewer} più recenti conservati`:''}.`;state.tone='ok';window.dispatchEvent(new CustomEvent('dealer:queue-changed'))}catch(err){state.message=`Ripristino non riuscito: ${errorLabel(err.message)}`;state.tone='bad'}finally{state.busy=false;render()}
}

function errorLabel(code){return ({backup_not_malu23:'Questo file non è un backup MALÙ23.',backup_version_unsupported:'Versione backup non supportata.',backup_wrong_dealer:'Il backup appartiene a un’altra concessionaria.',backup_stores_missing:'Backup incompleto.',backup_store_not_allowed:'Il backup contiene dati non riconosciuti.',backup_store_invalid:'Una sezione del backup è danneggiata.',backup_row_invalid:'Il backup contiene un elemento non valido.',backup_row_wrong_dealer:'Il backup contiene dati di un’altra concessionaria.',backup_too_many_records:'Backup troppo grande o non valido.'})[code]||code||'Errore inatteso'}
function injectStyle(){if($('#backupV161Style'))return;const style=document.createElement('style');style.id='backupV161Style';style.textContent=`.backup-panel{position:relative;overflow:hidden;background:radial-gradient(circle at 90% 0,rgba(211,162,75,.2),transparent 34%),linear-gradient(145deg,#101a2b,#090e18);color:#fff;border-radius:18px;padding:17px;display:grid;grid-template-columns:1fr auto;align-items:center;gap:16px;box-shadow:0 18px 42px rgba(10,18,32,.14)}.backup-panel small{font-size:7px;font-weight:950;letter-spacing:.7px;color:#d9bb79}.backup-panel h3{font-size:17px;margin:4px 0}.backup-panel p{font-size:8px;line-height:1.55;color:#bdc8d8;margin:0}.backup-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap;justify-content:flex-end}.backup-primary,.backup-secondary{min-height:44px;border:0;border-radius:11px;padding:10px 13px;font-size:9px;font-weight:950}.backup-primary{background:#fff;color:#111827}.backup-secondary{background:rgba(255,255,255,.11);color:#fff;border:1px solid rgba(255,255,255,.14)}.backup-message{grid-column:1/-1;border-radius:10px;padding:8px 10px;font-size:8px;background:rgba(46,148,99,.16);color:#c9f5df}.backup-message[data-tone="bad"]{background:rgba(210,65,72,.16);color:#ffd0d2}.backup-confirm{grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;gap:10px;background:rgba(255,255,255,.08);border-radius:11px;padding:10px}.backup-confirm b{font-size:9px}.backup-confirm span{display:block;font-size:7px;color:#bdc8d8;margin-top:3px}@media(max-width:720px){.backup-panel{grid-template-columns:1fr}.backup-actions{justify-content:stretch}.backup-primary,.backup-secondary{width:100%}.backup-confirm{align-items:stretch;flex-direction:column}}`;document.head.appendChild(style)}
async function render(){const root=$('#adminApp');if(!root||!canBackup())return;injectStyle();let panel=$('#backupPanel',root);if(!panel){panel=document.createElement('section');panel.id='backupPanel';panel.className='backup-panel';root.prepend(panel)}const last=await OfflineDB.getMeta(`backup:last:${dealerId()}`).catch(()=>null);panel.innerHTML=`<div><small>SICUREZZA DATI · BACKUP LOCALE</small><h3>I tuoi dati, al sicuro in un file</h3><p>Salva auto, clienti, costi, documenti e calendario. Il ripristino non cancella nulla e conserva i dati locali più recenti.</p></div><div class="backup-actions"><button class="backup-primary" id="backupNow" ${state.busy?'disabled':''}>${state.busy?'Attendi…':'Scarica backup adesso'}</button><button class="backup-secondary" id="backupChoose" ${state.busy?'disabled':''}>Ripristina backup</button><input id="backupFile" type="file" accept="application/json,.json" hidden></div><div class="backup-message" data-tone="${state.tone}">${state.message||`Ultimo backup su questo dispositivo: ${formatDate(last)}`}</div>${state.plan?`<div class="backup-confirm"><div><b>Backup verificato e compatibile</b><span>${backupSummary(state.plan)} · nessun dato verrà cancellato</span></div><button class="backup-primary" id="backupRestore" ${state.busy?'disabled':''}>Ripristina ${state.plan.total} elementi</button></div>`:''}`;$('#backupNow',panel).onclick=createBackup;$('#backupChoose',panel).onclick=()=>$('#backupFile',panel).click();$('#backupFile',panel).onchange=e=>chooseBackup(e.target.files?.[0]);$('#backupRestore',panel)?.addEventListener('click',restoreBackup)}

function boot(){const observer=new MutationObserver(()=>{if($('#adminApp')&&!$('#backupPanel'))render().catch(console.warn)});observer.observe(document.body,{childList:true,subtree:true});document.addEventListener('click',event=>{if(event.target.closest?.('.navbtn[data-view="admin"]'))setTimeout(()=>render().catch(console.warn),0)});render().catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
