import {OfflineDB,uuid} from './offline.js';
import {Session,accessToken,saveOfflineEntity} from './api.js';

const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>v?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(`${String(v).slice(0,10)}T12:00:00`)):'—';
const fmtBytes=n=>{n=Number(n||0);if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`};
const CATEGORIES=['LIBRETTO','COC','CONTRATTO','FATTURA_ACQUISTO','FATTURA_SPESA','IDENTITA_CLIENTE','ASSICURAZIONE','GARANZIA','DOCUMENTO_VEICOLO','ALTRO'];
const state={dealerId:null,documents:[],vehicles:[],customers:[],query:'',category:'ALL',status:'ACTIVE',selected:null};

function dealerId(){return Session.get()?.dealer?.id||'demo-malu23'}
function cfg(){return window.DEALER_CONFIG||{}}
function vehicleLabel(id){const v=state.vehicles.find(x=>x.id===id);return v?`${v.brand} ${v.model}${v.plate?` · ${v.plate}`:''}`:'—'}
function customerLabel(id){const c=state.customers.find(x=>x.id===id);return c?`${c.first_name} ${c.last_name}`:'—'}
function expiryState(d){if(!d.expires_on)return 'NONE';const t=new Date(`${d.expires_on}T23:59:59`).getTime(),now=Date.now(),soon=now+30*86400000;return t<now?'EXPIRED':t<=soon?'SOON':'OK'}
function statusLabel(d){if(d.inbox_status==='ARCHIVED')return 'ARCHIVIATO';const e=expiryState(d);if(e==='EXPIRED')return 'SCADUTO';if(e==='SOON')return 'IN SCADENZA';return d.storage_state==='CLOUD'?'CLOUD':'LOCALE'}
function storageKey(id,name){const safe=String(name||'documento').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-120);return `private/${dealerId()}/${id}/${safe}`}
function metadataOnly(row){const {blob,...rest}=row||{};return rest}

async function migrateLegacyBlobs(){const docs=await OfflineDB.list('documents',state.dealerId);for(const d of docs){if(d?.blob){await OfflineDB.put('document_blobs',{id:d.id,dealer_id:state.dealerId,document_id:d.id,blob:d.blob,updated_at:new Date().toISOString()});const clean={...d};delete clean.blob;clean.storage_state=clean.storage_state||'LOCAL';clean.object_key=clean.object_key||storageKey(clean.id,clean.original_name);clean.category=clean.category||'ALTRO';clean.title=clean.title||clean.original_name;await OfflineDB.put('documents',clean)}}}

async function load(){state.dealerId=dealerId();await migrateLegacyBlobs();[state.documents,state.vehicles,state.customers]=await Promise.all([OfflineDB.list('documents',state.dealerId),OfflineDB.list('vehicles',state.dealerId),OfflineDB.list('customers',state.dealerId)]);render()}

function injectUi(){
  if(!$('#documentsV06Style')){const s=document.createElement('style');s.id='documentsV06Style';s.textContent=`
  .mobile-nav{grid-template-columns:repeat(6,1fr)!important}.doc-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px}.doc-kpis>div{background:#fff;border:1px solid var(--line);border-radius:14px;padding:12px}.doc-kpis span{display:block;font-size:7px;color:var(--muted);font-weight:900}.doc-kpis b{display:block;font-size:16px;margin-top:4px}.doc-tools{display:grid;grid-template-columns:1fr 180px 180px auto;gap:8px;margin-bottom:12px}.doc-tools input,.doc-tools select{border:1px solid var(--line);background:#fff;border-radius:12px;padding:10px 12px;font-size:10px}.doc-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.doc-card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:13px;cursor:pointer}.doc-card.expired{border-color:#d98585}.doc-card.soon{border-color:#e5bd76}.doc-card h3{margin:5px 0 4px;font-size:13px}.doc-card p{margin:0;color:var(--muted);font-size:8px;line-height:1.55}.doc-meta{display:flex;gap:5px;flex-wrap:wrap;margin-top:10px}.doc-upload{display:none}.doc-overlay{position:fixed;inset:0;background:rgba(5,9,16,.58);z-index:135;display:flex;justify-content:flex-end}.doc-drawer{width:min(760px,100%);height:100%;overflow:auto;background:#f6f7f9}.doc-head{position:sticky;top:0;z-index:4;background:#0b1220;color:#fff;padding:18px 20px;display:flex;justify-content:space-between;gap:12px}.doc-head h2{margin:4px 0;font-size:22px}.doc-head p{margin:0;color:#aeb8c6;font-size:9px}.doc-close{border:0;background:rgba(255,255,255,.12);color:#fff;width:38px;height:38px;border-radius:12px}.doc-body{padding:14px;display:grid;gap:10px}.doc-box{background:#fff;border:1px solid var(--line);border-radius:16px;padding:14px}.doc-form{display:grid;grid-template-columns:1fr 1fr;gap:8px}.doc-field{display:grid;gap:5px}.doc-field.wide{grid-column:1/-1}.doc-field label{font-size:7px;font-weight:950;color:var(--muted)}.doc-field input,.doc-field select,.doc-field textarea{border:1px solid var(--line);border-radius:10px;padding:9px 10px;font-size:10px;background:#fff}.doc-field textarea{min-height:72px}.doc-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.doc-actions button{border:0;border-radius:9px;padding:8px 10px;font-size:8px;font-weight:900}.doc-actions .danger{background:#fff0f0;color:#9b2f35}.doc-file{display:flex;justify-content:space-between;gap:10px;align-items:center;background:#f7f8fa;border-radius:11px;padding:11px}.doc-file strong{font-size:9px}.doc-file small{display:block;color:var(--muted);font-size:7px;margin-top:2px}.doc-empty{grid-column:1/-1}
  @media(max-width:900px){.doc-kpis{grid-template-columns:1fr 1fr}.doc-tools{grid-template-columns:1fr}.doc-grid{grid-template-columns:1fr}.doc-form{grid-template-columns:1fr}.doc-drawer{width:100%}.doc-body{padding-bottom:100px}}
  `;document.head.appendChild(s)}
  const side=$('.side .nav');if(side&&!side.querySelector('[data-view="documenti"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.view='documenti';b.innerHTML='📄 &nbsp; Documenti';side.insertBefore(b,side.querySelector('[data-view="admin"]'))}
  const mobile=$('.mobile-nav');if(mobile&&!mobile.querySelector('[data-view="documenti"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.view='documenti';b.innerHTML='📄<small>DOC</small>';mobile.insertBefore(b,mobile.querySelector('[data-view="admin"]'))}
  const content=$('.content');if(content&&!content.querySelector('[data-view="documenti"]')){const section=document.createElement('section');section.className='view';section.dataset.view='documenti';section.innerHTML='<div class="section"><div><small>DOCUMENTI V0.6</small><h2>Archivio documentale</h2></div></div><div id="documentsApp"></div>';content.insertBefore(section,content.querySelector('[data-view="admin"]'))}
  const quick=$('.quick');if(quick&&!$('#quickDocuments')){const b=document.createElement('button');b.id='quickDocuments';b.innerHTML='<span class="ico">📄</span><b>Documenti</b><small>Archivio auto e clienti</small>';quick.appendChild(b);b.onclick=()=>openView()}
  $$('[data-view="documenti"].navbtn').forEach(b=>b.addEventListener('click',openView));
}

function openView(){ $$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view==='documenti'));$$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view==='documenti'));if($('#pageTitle'))$('#pageTitle').textContent='DOCUMENTI';window.scrollTo({top:0,behavior:'smooth'});load().catch(console.warn)}

function render(){const root=$('#documentsApp');if(!root)return;const active=state.documents.filter(d=>!d.deleted_at&&d.inbox_status!=='ARCHIVED'),exp=active.filter(d=>expiryState(d)==='EXPIRED').length,soon=active.filter(d=>expiryState(d)==='SOON').length,local=active.filter(d=>d.storage_state!=='CLOUD').length;root.innerHTML=`<div class="doc-kpis"><div><span>DOCUMENTI</span><b>${active.length}</b></div><div><span>IN SCADENZA</span><b>${soon}</b></div><div><span>SCADUTI</span><b>${exp}</b></div><div><span>SOLO LOCALI</span><b>${local}</b></div></div><div class="doc-tools"><input id="docSearch" value="${esc(state.query)}" placeholder="Cerca nome, targa, cliente…"><select id="docCategory"><option value="ALL">Tutte le categorie</option>${CATEGORIES.map(c=>`<option value="${c}" ${state.category===c?'selected':''}>${c.replaceAll('_',' ')}</option>`).join('')}</select><select id="docStatus"><option value="ACTIVE" ${state.status==='ACTIVE'?'selected':''}>Attivi</option><option value="EXPIRING" ${state.status==='EXPIRING'?'selected':''}>In scadenza</option><option value="EXPIRED" ${state.status==='EXPIRED'?'selected':''}>Scaduti</option><option value="ARCHIVED" ${state.status==='ARCHIVED'?'selected':''}>Archiviati</option></select><label class="btn" style="text-align:center">＋ Carica<input class="doc-upload" id="docUpload" type="file" multiple accept="application/pdf,image/*"></label></div><div class="doc-grid" id="docGrid"></div>`;
  $('#docSearch').oninput=e=>{state.query=e.target.value.toLowerCase();renderList()};$('#docCategory').onchange=e=>{state.category=e.target.value;renderList()};$('#docStatus').onchange=e=>{state.status=e.target.value;renderList()};$('#docUpload').onchange=e=>addFiles(e.target.files);renderList()}

function filtered(){return state.documents.filter(d=>!d.deleted_at).filter(d=>state.category==='ALL'||d.category===state.category).filter(d=>{if(state.status==='ARCHIVED')return d.inbox_status==='ARCHIVED';if(d.inbox_status==='ARCHIVED')return false;const e=expiryState(d);if(state.status==='EXPIRED')return e==='EXPIRED';if(state.status==='EXPIRING')return e==='SOON';return true}).filter(d=>{if(!state.query)return true;const hay=[d.title,d.original_name,d.category,vehicleLabel(d.vehicle_id),customerLabel(d.customer_id)].join(' ').toLowerCase();return hay.includes(state.query)}).sort((a,b)=>String(a.expires_on||'9999-12-31').localeCompare(String(b.expires_on||'9999-12-31'))||String(b.created_at||'').localeCompare(String(a.created_at||'')))}
function renderList(){const grid=$('#docGrid');if(!grid)return;const rows=filtered();grid.innerHTML=rows.length?rows.map(d=>{const ex=expiryState(d);return `<article class="doc-card ${ex==='EXPIRED'?'expired':ex==='SOON'?'soon':''}" data-doc-id="${esc(d.id)}"><div style="display:flex;justify-content:space-between;gap:8px"><span class="tag">${esc((d.category||'ALTRO').replaceAll('_',' '))}</span><span class="tag">${esc(statusLabel(d))}</span></div><h3>${esc(d.title||d.original_name||'Documento')}</h3><p>${esc(d.original_name||'')} · ${fmtBytes(d.size_bytes)}</p><div class="doc-meta">${d.vehicle_id?`<span class="tag">🚗 ${esc(vehicleLabel(d.vehicle_id))}</span>`:''}${d.customer_id?`<span class="tag">👤 ${esc(customerLabel(d.customer_id))}</span>`:''}${d.expires_on?`<span class="tag">⏰ ${fmtDate(d.expires_on)}</span>`:''}</div></article>`}).join(''):'<div class="empty doc-empty">Nessun documento trovato.</div>';$$('[data-doc-id]',grid).forEach(c=>c.onclick=()=>openDrawer(c.dataset.docId))}

async function addFiles(files){for(const file of [...files]){if(file.size>20*1024*1024){alert(`${file.name}: massimo 20 MB`);continue}const id=uuid(),now=new Date().toISOString(),row={id,dealer_id:state.dealerId,vehicle_id:null,customer_id:null,inbox_status:'UNASSIGNED',visibility:'PRIVATE',object_key:storageKey(id,file.name),original_name:file.name,title:file.name.replace(/\.[^.]+$/,''),category:'ALTRO',mime_type:file.type||'application/octet-stream',size_bytes:file.size,storage_state:'LOCAL',document_date:now.slice(0,10),expires_on:null,note:'',created_at:now,updated_at:now};await OfflineDB.put('document_blobs',{id,dealer_id:state.dealerId,document_id:id,blob:file,updated_at:now});const saved=await saveOfflineEntity('documents',state.dealerId,metadataOnly(row));state.documents.unshift(saved);if(navigator.onLine&&!cfg().demoMode&&cfg().workerUrl)await tryUpload(saved,file)}render();window.dispatchEvent(new CustomEvent('dealer:queue-changed'))}

async function tryUpload(doc,file){try{const token=await accessToken();const url=`${cfg().workerUrl}/documents/file?document_id=${encodeURIComponent(doc.id)}&file_name=${encodeURIComponent(doc.original_name)}`;const res=await fetch(url,{method:'PUT',headers:{authorization:`Bearer ${token}`,'x-dealer-id':state.dealerId,'content-type':doc.mime_type||'application/octet-stream'},body:file});if(!res.ok)throw new Error(`upload_${res.status}`);const result=await res.json();const updated=await saveOfflineEntity('documents',state.dealerId,{...metadataOnly(doc),object_key:result.object_key||doc.object_key,storage_state:'CLOUD'});const i=state.documents.findIndex(x=>x.id===doc.id);if(i>=0)state.documents[i]=updated}catch(err){console.warn('upload documento rimandato',err)}}

async function getBlob(doc){const local=await OfflineDB.get('document_blobs',doc.id);if(local?.blob)return local.blob;if(doc.storage_state==='CLOUD'&&cfg().workerUrl&&!cfg().demoMode){const token=await accessToken();const res=await fetch(`${cfg().workerUrl}/documents/file?document_id=${encodeURIComponent(doc.id)}`,{headers:{authorization:`Bearer ${token}`,'x-dealer-id':state.dealerId}});if(!res.ok)throw new Error(`download_${res.status}`);return res.blob()}throw new Error('file_not_available')}
async function openFile(doc){try{const blob=await getBlob(doc),url=URL.createObjectURL(blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch{alert('File non disponibile su questo dispositivo e non ancora presente nel cloud.') }}

function openDrawer(id){state.selected=id;const d=state.documents.find(x=>x.id===id);if(!d)return;let o=$('#docOverlay');if(!o){o=document.createElement('div');o.id='docOverlay';o.className='doc-overlay';o.hidden=true;o.innerHTML='<aside class="doc-drawer" id="docDrawer"></aside>';document.body.appendChild(o);o.addEventListener('click',e=>{if(e.target===o)closeDrawer()})}o.hidden=false;const dr=$('#docDrawer');dr.innerHTML=`<header class="doc-head"><div><small>${esc((d.category||'ALTRO').replaceAll('_',' '))}</small><h2>${esc(d.title||d.original_name)}</h2><p>${esc(d.original_name)} · ${fmtBytes(d.size_bytes)} · ${esc(statusLabel(d))}</p></div><button class="doc-close" id="docClose">✕</button></header><div class="doc-body"><section class="doc-box"><div class="doc-file"><div><strong>${esc(d.original_name)}</strong><small>${esc(d.mime_type||'file')} · privacy ${esc(d.visibility||'PRIVATE')}</small></div><button class="btn ghost" id="docOpen">Apri</button></div></section><section class="doc-box"><form id="docForm" class="doc-form"><div class="doc-field"><label>TITOLO</label><input name="title" value="${esc(d.title||'')}"></div><div class="doc-field"><label>CATEGORIA</label><select name="category">${CATEGORIES.map(c=>`<option value="${c}" ${d.category===c?'selected':''}>${c.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="doc-field"><label>DATA DOCUMENTO</label><input type="date" name="document_date" value="${esc(d.document_date||'')}"></div><div class="doc-field"><label>SCADENZA</label><input type="date" name="expires_on" value="${esc(d.expires_on||'')}"></div><div class="doc-field"><label>AUTO</label><select name="vehicle_id"><option value="">Nessuna</option>${state.vehicles.filter(v=>!v.deleted_at).map(v=>`<option value="${esc(v.id)}" ${d.vehicle_id===v.id?'selected':''}>${esc(vehicleLabel(v.id))}</option>`).join('')}</select></div><div class="doc-field"><label>CLIENTE</label><select name="customer_id"><option value="">Nessuno</option>${state.customers.filter(c=>!c.deleted_at).map(c=>`<option value="${esc(c.id)}" ${d.customer_id===c.id?'selected':''}>${esc(customerLabel(c.id))}</option>`).join('')}</select></div><div class="doc-field wide"><label>NOTE</label><textarea name="note">${esc(d.note||'')}</textarea></div><div class="doc-field wide"><button class="btn" type="submit">Salva scheda</button></div></form><div class="doc-actions"><button id="docArchive">Archivia</button>${d.storage_state!=='CLOUD'&&!cfg().demoMode&&cfg().workerUrl?'<button id="docRetry">Invia al cloud</button>':''}</div></section></div>`;$('#docClose').onclick=closeDrawer;$('#docOpen').onclick=()=>openFile(d);$('#docForm').onsubmit=saveDoc;$('#docArchive').onclick=archiveDoc;if($('#docRetry'))$('#docRetry').onclick=()=>retryUpload(d)}
function closeDrawer(){state.selected=null;const o=$('#docOverlay');if(o)o.hidden=true}

async function saveDoc(e){e.preventDefault();const d=state.documents.find(x=>x.id===state.selected),fd=new FormData(e.currentTarget);const row=await saveOfflineEntity('documents',state.dealerId,{...metadataOnly(d),title:String(fd.get('title')||'').trim()||d.original_name,category:String(fd.get('category')||'ALTRO'),document_date:String(fd.get('document_date')||'')||null,expires_on:String(fd.get('expires_on')||'')||null,vehicle_id:String(fd.get('vehicle_id')||'')||null,customer_id:String(fd.get('customer_id')||'')||null,inbox_status:(fd.get('vehicle_id')||fd.get('customer_id'))?'ASSIGNED':(d.inbox_status==='ARCHIVED'?'ARCHIVED':'UNASSIGNED'),note:String(fd.get('note')||'').trim()});const i=state.documents.findIndex(x=>x.id===row.id);if(i>=0)state.documents[i]=row;render();openDrawer(row.id);window.dispatchEvent(new CustomEvent('dealer:queue-changed'))}
async function archiveDoc(){const d=state.documents.find(x=>x.id===state.selected);if(!d)return;const row=await saveOfflineEntity('documents',state.dealerId,{...metadataOnly(d),inbox_status:'ARCHIVED'});const i=state.documents.findIndex(x=>x.id===row.id);if(i>=0)state.documents[i]=row;closeDrawer();render();window.dispatchEvent(new CustomEvent('dealer:queue-changed'))}
async function retryUpload(d){const local=await OfflineDB.get('document_blobs',d.id);if(!local?.blob)return alert('File locale non trovato.');await tryUpload(d,local.blob);await load();if(state.documents.find(x=>x.id===d.id))openDrawer(d.id)}

function init(){injectUi();state.dealerId=dealerId();window.addEventListener('dealer:queue-changed',()=>{if($('[data-view="documenti"]')?.classList.contains('active'))load().catch(()=>{})});load().catch(console.warn)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
