import {OfflineDB} from './offline.js';
import {Session} from './api.js';
import {buildReportRows,reportTotals,canViewFinancialReports,periodMatches} from './report-metrics.js?v=1.6.5';

const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n||0));
const state={dealerId:null,vehicles:[],financials:[],costs:[],invoices:[],contracts:[],period:'MONTH',query:''};
function cfg(){return window.DEALER_CONFIG||{}}
function dealerId(){return Session.get()?.dealer?.id||'demo-malu23'}
function canUse(){const p=Session.get()?.profile||{};if(p.role==='VENDITORE')return false;/* view_costs/finance_view are interpreted centrally */return canViewFinancialReports(p,!!cfg().demoMode)}
function financeRows(){return buildReportRows({vehicles:state.vehicles,financials:state.financials,costs:state.costs,invoices:state.invoices,contracts:state.contracts}).filter(r=>!state.query||[r.vehicle.brand,r.vehicle.model,r.vehicle.plate,r.vehicle.vin].join(' ').toLowerCase().includes(state.query)).sort((a,b)=>Number(b.margin??-Infinity)-Number(a.margin??-Infinity))}
async function load(){state.dealerId=dealerId();[state.vehicles,state.financials,state.costs,state.invoices,state.contracts]=await Promise.all([OfflineDB.list('vehicles',state.dealerId),OfflineDB.list('vehicle_financials',state.dealerId),OfflineDB.list('vehicle_costs',state.dealerId),OfflineDB.list('invoices',state.dealerId),OfflineDB.list('contracts',state.dealerId)]);render()}

function injectUi(){
 if(!$('#financeV10Style')){const s=document.createElement('style');s.id='financeV10Style';s.textContent=`body .mobile-nav{grid-template-columns:repeat(12,minmax(68px,1fr))!important;overflow-x:auto}.fin-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:12px}.fin-kpis>div{background:#fff;border:1px solid var(--line);border-radius:14px;padding:12px}.fin-kpis span{display:block;font-size:7px;color:var(--muted);font-weight:900}.fin-kpis b{display:block;font-size:15px;margin-top:4px}.fin-tools{display:grid;grid-template-columns:1fr 180px auto;gap:8px;margin-bottom:12px}.fin-tools input,.fin-tools select{border:1px solid var(--line);background:#fff;border-radius:12px;padding:10px 12px;font-size:10px}.fin-table{background:#fff;border:1px solid var(--line);border-radius:16px;overflow:auto}.fin-head,.fin-row{display:grid;grid-template-columns:minmax(190px,1.4fr) repeat(5,minmax(95px,.7fr));gap:8px;align-items:center;padding:11px 13px;min-width:850px}.fin-head{background:#f3f4f6;font-size:7px;font-weight:1000;color:var(--muted)}.fin-row{border-top:1px solid var(--line);font-size:9px}.fin-row strong{display:block;font-size:10px}.fin-row small{display:block;color:var(--muted);font-size:7px;margin-top:2px}.fin-pos{color:#18794e}.fin-neg{color:#b42318}.fin-pipeline{color:#9a6700}.fin-note{margin-top:10px;background:#fff8e8;border:1px solid #f0dfb2;border-radius:12px;padding:10px;font-size:8px;color:#6f581c;line-height:1.55}@media(max-width:900px){.fin-kpis{grid-template-columns:1fr 1fr}.fin-tools{grid-template-columns:1fr}}`;document.head.appendChild(s)}
 const side=$('.side .nav');if(side&&!side.querySelector('[data-view="finanze"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.view='finanze';b.innerHTML='📊 &nbsp; Finanze';side.insertBefore(b,side.querySelector('[data-view="admin"]'))}
 const mobile=$('.mobile-nav');if(mobile&&!mobile.querySelector('[data-view="finanze"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.view='finanze';b.innerHTML='📊<small>FINANZE</small>';mobile.insertBefore(b,mobile.querySelector('[data-view="admin"]'))}
 const content=$('.content');if(content&&!content.querySelector('[data-view="finanze"]')){const s=document.createElement('section');s.className='view';s.dataset.view='finanze';s.innerHTML='<div class="section"><div><small>FINANZE V1.1</small><h2>Margini e capitale</h2></div></div><div id="financeApp"></div>';content.insertBefore(s,content.querySelector('[data-view="admin"]'))}
 const quick=$('.quick');if(quick&&!$('#quickFinance')){const b=document.createElement('button');b.id='quickFinance';b.innerHTML='<span class="ico">📊</span><b>Finanze</b><small>Margini, capitale e incassi</small>';quick.appendChild(b);b.onclick=openView}
 $$('[data-view="finanze"].navbtn').forEach(b=>b.addEventListener('click',openView));
}
function openView(){if(!canUse()){alert('Non hai il permesso per vedere costi e margini.');return}$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view==='finanze'));$$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view==='finanze'));if($('#pageTitle'))$('#pageTitle').textContent='FINANZE';window.scrollTo({top:0,behavior:'smooth'});load().catch(console.warn)}
function render(){const root=$('#financeApp');if(!root)return;const rows=financeRows(),totals=reportTotals(rows,state.invoices,state.period);const delivered=rows.filter(r=>r.state==='DELIVERED'&&periodMatches(r.saleDate,state.period)),payables=state.invoices.filter(i=>!i.deleted_at&&i.invoice_type!=='SALE').reduce((s,i)=>s+Math.max(0,Number(i.total_amount||0)-Number(i.paid_amount||0)),0);root.innerHTML=`<div class="fin-kpis"><div><span>CAPITALE STOCK/PIPELINE</span><b>${money(totals.activeCapital)}</b></div><div><span>VENDUTO PERIODO</span><b>${money(totals.revenue)}</b></div><div><span>MARGINE GESTIONALE</span><b class="${totals.margin<0?'fin-neg':'fin-pos'}">${money(totals.margin)}</b></div><div><span>DA INCASSARE</span><b>${money(totals.receivables)}</b></div><div><span>DA PAGARE</span><b>${money(payables)}</b></div></div><div class="fin-tools"><input id="finSearch" value="${esc(state.query)}" placeholder="Cerca auto, targa, telaio…"><select id="finPeriod"><option value="MONTH" ${state.period==='MONTH'?'selected':''}>Mese corrente</option><option value="YEAR" ${state.period==='YEAR'?'selected':''}>Anno corrente</option><option value="ALL" ${state.period==='ALL'?'selected':''}>Tutto</option></select><button class="btn ghost" id="finPrint">Stampa report</button></div><div class="fin-table"><div class="fin-head"><div>AUTO</div><div>ACQUISTO</div><div>SPESE</div><div>COSTO REALE</div><div>VENDITA</div><div>MARGINE</div></div><div id="finRows"></div></div><div class="fin-note">Ricavi e margini vengono riconosciuti solo alla consegna. Prenotate e da consegnare restano pipeline e continuano a pesare sul capitale attivo. Il margine è gestionale lordo: vendita − acquisto − spese veicolo; IVA, imposte e costi generali non vengono stimati automaticamente. Vendite consegnate nel periodo: ${delivered.length}.</div>`;$('#finSearch').oninput=e=>{state.query=e.target.value.toLowerCase();renderRows()};$('#finPeriod').onchange=e=>{state.period=e.target.value;render()};$('#finPrint').onclick=()=>window.print();renderRows()}
function renderRows(){const root=$('#finRows');if(!root)return;const rows=financeRows();root.innerHTML=rows.length?rows.map(r=>{const stateLabel=r.state==='DELIVERED'?'Consegnata':r.state==='PIPELINE'?'In corso':'Stock';const sale=r.agreedSale>0?money(r.agreedSale):'—';const margin=r.state==='DELIVERED'?money(r.margin):'—';return `<div class="fin-row"><div><strong>${esc(`${r.vehicle.brand||''} ${r.vehicle.model||''}`.trim())}</strong><small>${esc(r.vehicle.plate||r.vehicle.vin||'—')} · ${stateLabel}</small></div><div>${money(r.purchase)}</div><div>${money(r.expenses)}</div><div><strong>${money(r.realCost)}</strong></div><div class="${r.state==='PIPELINE'?'fin-pipeline':''}">${sale}${r.state==='PIPELINE'&&r.agreedSale>0?' · in corso':''}</div><div><strong class="${r.state==='DELIVERED'?(r.margin<0?'fin-neg':'fin-pos'):''}">${margin}</strong></div></div>`}).join(''):'<div class="empty" style="margin:12px">Nessun veicolo.</div>'}

window.addEventListener('dealer:data-updated',()=>load().catch(()=>{}));
injectUi();
