import {OfflineDB} from './offline.js';
import {Session} from './api.js';

const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n||0));
const state={dealerId:null,vehicles:[],financials:[],costs:[],invoices:[],contracts:[],period:'MONTH',query:''};
function cfg(){return window.DEALER_CONFIG||{}}
function dealerId(){return Session.get()?.dealer?.id||'demo-malu23'}
function canUse(){const p=Session.get()?.profile||{};return ['ADMIN','AMMINISTRAZIONE'].includes(p.role)||p.permissions?.view_costs===true||p.permissions?.finance_view===true||cfg().demoMode}
function financial(id){return state.financials.find(f=>f.vehicle_id===id)||null}
function vehicleCosts(id){return state.costs.filter(c=>c.vehicle_id===id).reduce((s,c)=>s+Number(c.amount||0),0)}
function saleInvoice(id){return state.invoices.filter(i=>!i.deleted_at&&i.invoice_type==='SALE'&&i.vehicle_id===id).sort((a,b)=>String(b.issue_date||'').localeCompare(String(a.issue_date||'')))[0]||null}
function saleContract(id){return state.contracts.filter(c=>c.template_code==='VENDITA'&&c.vehicle_id===id&&c.sale_stage!=='CANCELLED').sort((a,b)=>String(b.contract_date||'').localeCompare(String(a.contract_date||'')))[0]||null}
function saleAmount(id){const inv=saleInvoice(id),c=saleContract(id),v=state.vehicles.find(x=>x.id===id);return Number(inv?.total_amount||c?.price||v?.sale_price||0)}
function saleDate(id){const inv=saleInvoice(id),c=saleContract(id);return inv?.issue_date||String(c?.delivered_at||c?.contract_date||'').slice(0,10)||''}
function totalCost(id){return Number(financial(id)?.purchase_price||0)+vehicleCosts(id)}
function isSold(v){return ['VENDUTA','DA_CONSEGNARE','CONSEGNATA'].includes(v.status)||!!saleAmount(v.id)}
function inPeriod(date){if(state.period==='ALL')return true;if(!date)return false;const d=String(date).slice(0,10),now=new Date(),y=String(now.getFullYear()),m=`${y}-${String(now.getMonth()+1).padStart(2,'0')}`;return state.period==='YEAR'?d.startsWith(y):d.startsWith(m)}
function financeRows(){return state.vehicles.filter(v=>!v.deleted_at).map(v=>{const purchase=Number(financial(v.id)?.purchase_price||0),costs=vehicleCosts(v.id),total=purchase+costs,sale=saleAmount(v.id);return {v,purchase,costs,total,sale,margin:sale-total,date:saleDate(v.id),sold:isSold(v)}}).filter(r=>!state.query||[r.v.brand,r.v.model,r.v.plate,r.v.vin].join(' ').toLowerCase().includes(state.query)).sort((a,b)=>b.margin-a.margin)}
async function load(){state.dealerId=dealerId();[state.vehicles,state.financials,state.costs,state.invoices,state.contracts]=await Promise.all([OfflineDB.list('vehicles',state.dealerId),OfflineDB.list('vehicle_financials',state.dealerId),OfflineDB.list('vehicle_costs',state.dealerId),OfflineDB.list('invoices',state.dealerId),OfflineDB.list('contracts',state.dealerId)]);render()}

function injectUi(){
 if(!$('#financeV10Style')){const s=document.createElement('style');s.id='financeV10Style';s.textContent=`body .mobile-nav{grid-template-columns:repeat(12,minmax(68px,1fr))!important;overflow-x:auto}.fin-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:12px}.fin-kpis>div{background:#fff;border:1px solid var(--line);border-radius:14px;padding:12px}.fin-kpis span{display:block;font-size:7px;color:var(--muted);font-weight:900}.fin-kpis b{display:block;font-size:15px;margin-top:4px}.fin-tools{display:grid;grid-template-columns:1fr 180px auto;gap:8px;margin-bottom:12px}.fin-tools input,.fin-tools select{border:1px solid var(--line);background:#fff;border-radius:12px;padding:10px 12px;font-size:10px}.fin-table{background:#fff;border:1px solid var(--line);border-radius:16px;overflow:auto}.fin-head,.fin-row{display:grid;grid-template-columns:minmax(190px,1.4fr) repeat(5,minmax(95px,.7fr));gap:8px;align-items:center;padding:11px 13px;min-width:850px}.fin-head{background:#f3f4f6;font-size:7px;font-weight:1000;color:var(--muted)}.fin-row{border-top:1px solid var(--line);font-size:9px}.fin-row strong{display:block;font-size:10px}.fin-row small{display:block;color:var(--muted);font-size:7px;margin-top:2px}.fin-pos{color:#18794e}.fin-neg{color:#b42318}.fin-note{margin-top:10px;background:#fff8e8;border:1px solid #f0dfb2;border-radius:12px;padding:10px;font-size:8px;color:#6f581c;line-height:1.55}@media(max-width:900px){.fin-kpis{grid-template-columns:1fr 1fr}.fin-tools{grid-template-columns:1fr}}`;document.head.appendChild(s)}
 const side=$('.side .nav');if(side&&!side.querySelector('[data-view="finanze"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.view='finanze';b.innerHTML='📊 &nbsp; Finanze';side.insertBefore(b,side.querySelector('[data-view="admin"]'))}
 const mobile=$('.mobile-nav');if(mobile&&!mobile.querySelector('[data-view="finanze"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.view='finanze';b.innerHTML='📊<small>FINANZE</small>';mobile.insertBefore(b,mobile.querySelector('[data-view="admin"]'))}
 const content=$('.content');if(content&&!content.querySelector('[data-view="finanze"]')){const s=document.createElement('section');s.className='view';s.dataset.view='finanze';s.innerHTML='<div class="section"><div><small>FINANZE V1.0</small><h2>Margini e capitale</h2></div></div><div id="financeApp"></div>';content.insertBefore(s,content.querySelector('[data-view="admin"]'))}
 const quick=$('.quick');if(quick&&!$('#quickFinance')){const b=document.createElement('button');b.id='quickFinance';b.innerHTML='<span class="ico">📊</span><b>Finanze</b><small>Margini, capitale e incassi</small>';quick.appendChild(b);b.onclick=openView}
 $$('[data-view="finanze"].navbtn').forEach(b=>b.addEventListener('click',openView));
}
function openView(){if(!canUse()){alert('Non hai il permesso per vedere costi e margini.');return}$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view==='finanze'));$$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view==='finanze'));if($('#pageTitle'))$('#pageTitle').textContent='FINANZE';window.scrollTo({top:0,behavior:'smooth'});load().catch(console.warn)}
function render(){const root=$('#financeApp');if(!root)return;const rows=financeRows(),stock=rows.filter(r=>!r.sold),sold=rows.filter(r=>r.sold&&inPeriod(r.date));const invested=stock.reduce((s,r)=>s+r.total,0),revenue=sold.reduce((s,r)=>s+r.sale,0),margin=sold.reduce((s,r)=>s+r.margin,0);const receivables=state.invoices.filter(i=>!i.deleted_at&&i.invoice_type==='SALE').reduce((s,i)=>s+Math.max(0,Number(i.total_amount||0)-Number(i.paid_amount||0)),0);const payables=state.invoices.filter(i=>!i.deleted_at&&i.invoice_type!=='SALE').reduce((s,i)=>s+Math.max(0,Number(i.total_amount||0)-Number(i.paid_amount||0)),0);root.innerHTML=`<div class="fin-kpis"><div><span>CAPITALE STOCK</span><b>${money(invested)}</b></div><div><span>VENDUTO PERIODO</span><b>${money(revenue)}</b></div><div><span>MARGINE GESTIONALE</span><b class="${margin<0?'fin-neg':'fin-pos'}">${money(margin)}</b></div><div><span>DA INCASSARE</span><b>${money(receivables)}</b></div><div><span>DA PAGARE</span><b>${money(payables)}</b></div></div><div class="fin-tools"><input id="finSearch" value="${esc(state.query)}" placeholder="Cerca auto, targa, telaio…"><select id="finPeriod"><option value="MONTH" ${state.period==='MONTH'?'selected':''}>Mese corrente</option><option value="YEAR" ${state.period==='YEAR'?'selected':''}>Anno corrente</option><option value="ALL" ${state.period==='ALL'?'selected':''}>Tutto</option></select><button class="btn ghost" id="finPrint">Stampa report</button></div><div class="fin-table"><div class="fin-head"><div>AUTO</div><div>ACQUISTO</div><div>SPESE</div><div>COSTO REALE</div><div>VENDITA</div><div>MARGINE</div></div><div id="finRows"></div></div><div class="fin-note">Il margine mostrato è gestionale lordo: prezzo vendita − acquisto − spese veicolo. IVA, imposte e costi generali aziendali non vengono stimati automaticamente.</div>`;$('#finSearch').oninput=e=>{state.query=e.target.value.toLowerCase();renderRows()};$('#finPeriod').onchange=e=>{state.period=e.target.value;render()};$('#finPrint').onclick=()=>window.print();renderRows()}
function renderRows(){const root=$('#finRows');if(!root)return;const rows=financeRows();root.innerHTML=rows.length?rows.map(r=>`<div class="fin-row"><div><strong>${esc(`${r.v.brand||''} ${r.v.model||''}`.trim())}</strong><small>${esc(r.v.plate||r.v.vin||'—')} · ${r.sold?'Venduta/assegnata':'Stock'}</small></div><div>${money(r.purchase)}</div><div>${money(r.costs)}</div><div><strong>${money(r.total)}</strong></div><div>${r.sale?money(r.sale):'—'}</div><div><strong class="${r.sale?(r.margin<0?'fin-neg':'fin-pos'):''}">${r.sale?money(r.margin):'—'}</strong></div></div>`).join(''):'<div class="empty" style="margin:12px">Nessun veicolo.</div>'}

window.addEventListener('dealer:data-updated',()=>load().catch(()=>{}));
injectUi();

