import {OfflineDB,uuid} from './offline.js';
import {Session} from './api.js';

const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n||0));
const TYPES={POST:'POST',REEL:'REEL',STORY:'STORIA'};
const STATUS={DRAFT:'BOZZA',READY:'PRONTO',SCHEDULED:'PROGRAMMATO',PUBLISHED:'PUBBLICATO',ERROR:'ERRORE'};
const state={dealerId:null,vehicles:[],media:[],items:[],query:'',status:'ALL'};
const cfg=()=>window.DEALER_CONFIG||{};
const dealerId=()=>Session.get()?.dealer?.id||'demo-malu23';
const storageKey=id=>`instagram_posts:${id}`;
function canUse(){const p=Session.get()?.profile||{};return ['ADMIN','VENDITORE'].includes(p.role)||p.permissions?.instagram_view===true||cfg().demoMode}
function canWrite(){const p=Session.get()?.profile||{};return ['ADMIN','VENDITORE'].includes(p.role)||p.permissions?.instagram_manage===true||cfg().demoMode}
function vehicle(id){return state.vehicles.find(v=>v.id===id)||null}
function vehicleLabel(v){return v?`${v.brand||''} ${v.model||''}${v.version?` ${v.version}`:''}${v.plate?` · ${v.plate}`:''}`.trim():'—'}
function vehicleMedia(id){return state.media.filter(m=>m.vehicle_id===id&&!m.deleted_at).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0))}
function defaultCaption(v){if(!v)return '';return [`🚗 ${v.brand||''} ${v.model||''}${v.version?` ${v.version}`:''}`.trim(),v.year?`📅 ${v.year}`:'',v.mileage?`🛣️ ${Number(v.mileage).toLocaleString('it-IT')} km`:'',v.asking_price?`💶 ${money(v.asking_price)}`:'','Disponibile da MALÙ23 CARS.','Scrivici in DM per informazioni o appuntamento.'].filter(Boolean).join('\n')}
function defaultTags(v){const brand=String(v?.brand||'').replace(/[^a-zA-Z0-9]/g,''),model=String(v?.model||'').replace(/[^a-zA-Z0-9]/g,'');return ['#Malu23Cars','#AutoUsate','#AutoInVendita',brand&&`#${brand}`,model&&`#${model}`].filter(Boolean).join(' ')}
async function saveLocal(){await OfflineDB.setMeta(storageKey(state.dealerId),state.items)}
async function loadLocal(){const rows=await OfflineDB.getMeta(storageKey(state.dealerId));return Array.isArray(rows)?rows:[]}
function authHeaders(){const c=cfg(),token=Session.accessToken();return {'content-type':'application/json',apikey:c.supabasePublishableKey,authorization:`Bearer ${token}`}}
async function cloudList(){const c=cfg();if(c.demoMode||!navigator.onLine||!c.supabaseUrl||!c.supabasePublishableKey||!Session.accessToken())return null;const r=await fetch(`${c.supabaseUrl}/rest/v1/instagram_posts?dealer_id=eq.${encodeURIComponent(state.dealerId)}&deleted_at=is.null&select=*&order=updated_at.desc`,{headers:authHeaders()});if(!r.ok)throw new Error(`instagram_cloud_${r.status}`);return r.json()}
async function cloudUpsert(row){const c=cfg();if(c.demoMode||!navigator.onLine||!c.supabaseUrl||!c.supabasePublishableKey||!Session.accessToken())return false;const payload={...row};delete payload.sync_state;const r=await fetch(`${c.supabaseUrl}/rest/v1/instagram_posts?on_conflict=id`,{method:'POST',headers:{...authHeaders(),Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(`instagram_sync_${r.status}`);return true}
async function syncCloud(){try{for(const row of state.items.filter(x=>x.sync_state==='PENDING')){await cloudUpsert(row);row.sync_state='SYNCED'}const server=await cloudList();if(server){const map=new Map(state.items.map(x=>[x.id,x]));for(const remote of server){const local=map.get(remote.id);if(!local||String(remote.updated_at||'')>String(local.updated_at||''))map.set(remote.id,{...remote,sync_state:'SYNCED'})}state.items=[...map.values()];await saveLocal()}return true}catch(err){console.warn('Instagram sync',err);return false}}
async function load(){state.dealerId=dealerId();[state.vehicles,state.media,state.items]=await Promise.all([OfflineDB.list('vehicles',state.dealerId),OfflineDB.list('vehicle_media',state.dealerId),loadLocal()]);await syncCloud();render()}
function injectUi(){
 if(!$('#instagramV12Style')){const s=document.createElement('style');s.id='instagramV12Style';s.textContent=`body .mobile-nav{grid-template-columns:repeat(12,1fr)!important}.ig-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px}.ig-kpis>div,.ig-card,.ig-box{background:#fff;border:1px solid var(--line);border-radius:15px;padding:13px}.ig-kpis span{display:block;font-size:7px;color:var(--muted);font-weight:900}.ig-kpis b{display:block;font-size:15px;margin-top:4px}.ig-tools{display:grid;grid-template-columns:1fr 180px auto;gap:8px;margin-bottom:12px}.ig-tools input,.ig-tools select,.ig-field input,.ig-field select,.ig-field textarea{border:1px solid var(--line);background:#fff;border-radius:11px;padding:10px 11px;font-size:10px}.ig-grid{display:grid;gap:8px}.ig-card{display:grid;grid-template-columns:minmax(0,1.2fr) .5fr .5fr auto;gap:10px;align-items:center;cursor:pointer}.ig-card strong{font-size:10px}.ig-card small{display:block;color:var(--muted);font-size:7px;margin-top:3px}.ig-card .caption{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:460px}.ig-overlay{position:fixed;inset:0;background:rgba(5,9,16,.58);z-index:180;display:flex;justify-content:flex-end}.ig-drawer{width:min(820px,100%);height:100%;overflow:auto;background:#f6f7f9}.ig-head{position:sticky;top:0;z-index:4;background:#0b1220;color:#fff;padding:18px 20px;display:flex;justify-content:space-between}.ig-head h2{margin:4px 0;font-size:22px}.ig-body{padding:14px;display:grid;gap:10px}.ig-form{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.ig-field{display:grid;gap:5px}.ig-field.wide{grid-column:1/-1}.ig-field label{font-size:7px;font-weight:950;color:var(--muted)}.ig-field textarea{min-height:130px;resize:vertical}.ig-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.ig-note{font-size:8px;line-height:1.55;color:var(--muted)}.ig-preview{background:linear-gradient(145deg,#18181b,#09090b);color:#fff;border-radius:18px;padding:16px}.ig-preview b{display:block;margin-bottom:8px}.ig-preview pre{white-space:pre-wrap;font:inherit;font-size:10px;line-height:1.5;margin:0;color:#e4e4e7}@media(max-width:900px){.ig-kpis{grid-template-columns:1fr 1fr}.ig-tools,.ig-form,.ig-card{grid-template-columns:1fr}.ig-drawer{width:100%}.ig-body{padding-bottom:100px}}`;document.head.appendChild(s)}
 const side=$('.side .nav');if(side&&!side.querySelector('[data-view="instagram"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.view='instagram';b.innerHTML='◎ &nbsp; Instagram';side.insertBefore(b,side.querySelector('[data-view="admin"]'))}
 const mobile=$('.mobile-nav');if(mobile&&!mobile.querySelector('[data-view="instagram"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.view='instagram';b.innerHTML='◎<small>INSTAGRAM</small>';mobile.insertBefore(b,mobile.querySelector('[data-view="admin"]'))}
 const content=$('.content');if(content&&!content.querySelector('[data-view="instagram"]')){const s=document.createElement('section');s.className='view';s.dataset.view='instagram';s.innerHTML='<div class="section"><div><small>INSTAGRAM V1.2</small><h2>Contenuti e pubblicazione</h2></div></div><div id="instagramApp"></div>';content.insertBefore(s,content.querySelector('[data-view="admin"]'))}
 $$('[data-view="instagram"].navbtn').forEach(b=>b.addEventListener('click',()=>openView(false)));
}
function openView(create=false){if(!canUse()){alert('Non hai il permesso per Instagram.');return}$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view==='instagram'));$$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view==='instagram'));if($('#pageTitle'))$('#pageTitle').textContent='INSTAGRAM';window.scrollTo({top:0,behavior:'smooth'});load().then(()=>{if(create)openDrawer(null)}).catch(console.warn)}
function rows(){return state.items.filter(x=>!x.deleted_at).filter(x=>state.status==='ALL'||x.status===state.status).filter(x=>!state.query||[x.caption,vehicleLabel(vehicle(x.vehicle_id)),x.content_type,x.status].join(' ').toLowerCase().includes(state.query)).sort((a,b)=>String(b.updated_at||'').localeCompare(String(a.updated_at||'')))}
function render(){const root=$('#instagramApp');if(!root)return;const all=state.items.filter(x=>!x.deleted_at);root.innerHTML=`<div class="ig-kpis"><div><span>BOZZE</span><b>${all.filter(x=>x.status==='DRAFT').length}</b></div><div><span>PRONTI</span><b>${all.filter(x=>x.status==='READY').length}</b></div><div><span>PROGRAMMATI</span><b>${all.filter(x=>x.status==='SCHEDULED').length}</b></div><div><span>PUBBLICATI</span><b>${all.filter(x=>x.status==='PUBLISHED').length}</b></div></div><div class="ig-tools"><input id="igSearch" value="${esc(state.query)}" placeholder="Cerca auto o caption…"><select id="igStatus"><option value="ALL">Tutti gli stati</option>${Object.entries(STATUS).map(([k,v])=>`<option value="${k}" ${state.status===k?'selected':''}>${v}</option>`).join('')}</select><button class="btn" id="newIgBtn" ${canWrite()?'':'disabled'}>＋ Contenuto</button></div><div class="ig-grid" id="igGrid"></div>`;$('#igSearch').oninput=e=>{state.query=e.target.value.toLowerCase();renderList()};$('#igStatus').onchange=e=>{state.status=e.target.value;renderList()};$('#newIgBtn').onclick=()=>openDrawer(null);renderList()}
function renderList(){const grid=$('#igGrid');if(!grid)return;const list=rows();grid.innerHTML=list.length?list.map(x=>`<article class="ig-card" data-ig-id="${esc(x.id)}"><div><span class="tag">${esc(TYPES[x.content_type]||x.content_type||'POST')}</span><strong style="display:block;margin-top:5px">${esc(vehicleLabel(vehicle(x.vehicle_id)))}</strong><small class="caption">${esc(x.caption||'Nessuna caption')}</small></div><div><small>STATO</small><strong>${esc(STATUS[x.status]||x.status)}</strong></div><div><small>PROGRAMMAZIONE</small><strong>${x.scheduled_at?new Date(x.scheduled_at).toLocaleString('it-IT'):'—'}</strong></div><span class="tag">${x.media_count||0} MEDIA</span></article>`).join(''):'<div class="empty">Nessun contenuto Instagram.</div>';$$('[data-ig-id]',grid).forEach(x=>x.onclick=()=>openDrawer(x.dataset.igId))}
function vehicleOptions(selected){return `<option value="">— Seleziona auto —</option>`+state.vehicles.filter(v=>!v.deleted_at).map(v=>`<option value="${esc(v.id)}" ${v.id===selected?'selected':''}>${esc(vehicleLabel(v))}</option>`).join('')}
function openDrawer(id){const item=id?state.items.find(x=>x.id===id):null;let o=$('#igOverlay');if(!o){o=document.createElement('div');o.id='igOverlay';o.className='ig-overlay';o.hidden=true;o.innerHTML='<aside class="ig-drawer" id="igDrawer"></aside>';document.body.appendChild(o);o.addEventListener('click',e=>{if(e.target===o)o.hidden=true})}o.hidden=false;const v=vehicle(item?.vehicle_id),mediaCount=v?vehicleMedia(v.id).length:0;$('#igDrawer').innerHTML=`<header class="ig-head"><div><small>${item?'CONTENUTO':'NUOVO CONTENUTO'}</small><h2>${esc(item?vehicleLabel(v):'Instagram')}</h2></div><button class="sale-close" id="igClose">×</button></header><div class="ig-body"><form class="ig-box ig-form" id="igForm"><input type="hidden" name="id" value="${esc(item?.id||'')}"><div class="ig-field wide"><label>AUTO</label><select name="vehicle_id" required>${vehicleOptions(item?.vehicle_id)}</select></div><div class="ig-field"><label>FORMATO</label><select name="content_type">${Object.entries(TYPES).map(([k,val])=>`<option value="${k}" ${(item?.content_type||'POST')===k?'selected':''}>${val}</option>`).join('')}</select></div><div class="ig-field"><label>STATO</label><select name="status">${Object.entries(STATUS).map(([k,val])=>`<option value="${k}" ${(item?.status||'DRAFT')===k?'selected':''}>${val}</option>`).join('')}</select></div><div class="ig-field wide"><label>CAPTION</label><textarea name="caption">${esc(item?.caption||defaultCaption(v))}</textarea></div><div class="ig-field wide"><label>HASHTAG</label><input name="hashtags" value="${esc(item?.hashtags||defaultTags(v))}"></div><div class="ig-field"><label>PROGRAMMAZIONE</label><input type="datetime-local" name="scheduled_at" value="${item?.scheduled_at?esc(String(item.scheduled_at).slice(0,16)):''}"></div><div class="ig-field"><label>MEDIA GARAGE</label><input value="${mediaCount} file collegati" disabled></div><div class="ig-field wide"><label>URL MEDIA PUBBLICO / TEMPORANEO</label><input name="media_url" value="${esc(item?.media_url||'')}" placeholder="Richiesto dalla pubblicazione API Meta"></div><div class="ig-field wide"><label>NOTE</label><textarea name="notes" style="min-height:70px">${esc(item?.notes||'')}</textarea></div><div class="ig-actions wide"><button class="btn" type="submit">Salva</button><button class="btn ghost" type="button" id="igAutoCaption">Genera caption auto</button>${item?'<button class="btn ghost" type="button" id="igCopy">Copia caption</button>':''}</div></form><div class="ig-preview"><b>ANTEPRIMA TESTO</b><pre id="igPreview"></pre></div><div class="ig-box ig-note"><b>Pubblicazione ufficiale Meta</b><br>Predisposto per account Instagram professionali. Token e segreti restano lato server; il browser conserva solo contenuto e stato editoriale.</div></div>`;
 $('#igClose').onclick=()=>o.hidden=true;const form=$('#igForm'),preview=()=>{$('#igPreview').textContent=[form.caption.value,form.hashtags.value].filter(Boolean).join('\n\n')};form.caption.oninput=preview;form.hashtags.oninput=preview;form.vehicle_id.onchange=()=>{const nv=vehicle(form.vehicle_id.value);form.caption.value=defaultCaption(nv);form.hashtags.value=defaultTags(nv);preview()};$('#igAutoCaption').onclick=()=>{const nv=vehicle(form.vehicle_id.value);form.caption.value=defaultCaption(nv);form.hashtags.value=defaultTags(nv);preview()};if($('#igCopy'))$('#igCopy').onclick=async()=>{await navigator.clipboard.writeText([form.caption.value,form.hashtags.value].filter(Boolean).join('\n\n'));alert('Caption copiata.')};form.onsubmit=saveItem;preview()}
async function saveItem(e){e.preventDefault();if(!canWrite())return;const f=new FormData(e.currentTarget),vid=String(f.get('vehicle_id')||''),v=vehicle(vid);if(!v)return alert('Seleziona un’auto.');const current=String(f.get('id')||'')?state.items.find(x=>x.id===f.get('id')):null;const row={...(current||{}),id:current?.id||uuid(),dealer_id:state.dealerId,vehicle_id:vid,content_type:String(f.get('content_type')||'POST'),status:String(f.get('status')||'DRAFT'),caption:String(f.get('caption')||'').trim(),hashtags:String(f.get('hashtags')||'').trim(),scheduled_at:f.get('scheduled_at')?new Date(String(f.get('scheduled_at'))).toISOString():null,media_url:String(f.get('media_url')||'').trim()||null,media_count:vehicleMedia(vid).length,notes:String(f.get('notes')||'').trim()||null,published_at:String(f.get('status'))==='PUBLISHED'?(current?.published_at||new Date().toISOString()):null,created_at:current?.created_at||new Date().toISOString(),updated_at:new Date().toISOString(),sync_state:'PENDING'};const i=state.items.findIndex(x=>x.id===row.id);if(i>=0)state.items[i]=row;else state.items.push(row);await saveLocal();try{if(await cloudUpsert(row)){row.sync_state='SYNCED';await saveLocal()}}catch(err){console.warn('Instagram save sync',err)}$('#igOverlay').hidden=true;render()}

injectUi();
window.addEventListener('dealer:data-updated',()=>load().catch(()=>{}));
window.addEventListener('online',()=>syncCloud().then(render).catch(()=>{}));
