import {OfflineDB} from './offline.js';
import {Session} from './api.js';
import {instagramContentHealth,normalizePublicMediaUrl} from './instagram-readiness.js?v=1.6.4';

const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
let items=[];let queued=false;
const dealerId=()=>Session.get()?.dealer?.id||null;
const storageKey=id=>`instagram_posts:${id}`;
const label=code=>({MISSING_VEHICLE:'seleziona auto',CAPTION_TOO_SHORT:'caption troppo corta',MISSING_MEDIA_URL:'manca URL media pubblico',INVALID_MEDIA_URL:'URL media non pubblico/HTTPS',MISSING_SCHEDULE:'manca programmazione',SCHEDULE_NOT_FUTURE:'programmazione non futura',UNVERIFIED_PUBLISHED:'pubblicazione non verificata da Meta',ERROR_WITHOUT_NOTE:'errore senza nota'})[code]||code;

async function load(){const id=dealerId();const rows=id?await OfflineDB.getMeta(storageKey(id)):[];items=Array.isArray(rows)?rows:[];enhance()}
function injectStyle(){if($('#instagramSafetyStyle'))return;const s=document.createElement('style');s.id='instagramSafetyStyle';s.textContent=`.ig-health{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px}.ig-health>div{background:#fff;border:1px solid var(--line);border-radius:14px;padding:11px}.ig-health span{display:block;font-size:7px;font-weight:900;color:var(--muted)}.ig-health b{display:block;font-size:15px;margin-top:4px}.ig-health-note{grid-column:1/-1!important;background:#fffaf0!important}.ig-quality{grid-column:1/-1;padding:9px 10px;border-radius:10px;background:#fff3e3;color:#7b4c0e;font-size:8px;line-height:1.45}.ig-quality.ok{background:#edf6f1;color:#176442}@media(max-width:900px){.ig-health{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function renderHealth(){const root=$('#instagramApp');if(!root)return;const live=items.filter(x=>!x.deleted_at),ready=live.filter(x=>x.status==='READY').length,scheduled=live.filter(x=>x.status==='SCHEDULED').length,published=live.filter(x=>x.status==='PUBLISHED'&&instagramContentHealth(x).ready).length,issues=live.filter(x=>instagramContentHealth(x).blocking.length).length;let panel=$('#instagramHealth');if(!panel){panel=document.createElement('div');panel.id='instagramHealth';panel.className='ig-health';root.prepend(panel)}const html=`<div><span>PRONTI</span><b>${ready}</b></div><div><span>PROGRAMMATI</span><b>${scheduled}</b></div><div><span>PUBBLICATI VERIFICATI</span><b>${published}</b></div><div><span>DA SISTEMARE</span><b>${issues}</b></div>${issues?'<div class="ig-health-note"><span>CONTROLLO QUALITÀ</span><b style="font-size:9px">Pronto e Programmato richiedono auto, caption e media HTTPS pubblico. Pubblicato viene confermato da Meta/server, non manualmente.</b></div>':''}`;if(panel.innerHTML!==html)panel.innerHTML=html}
function formCandidate(form){const f=new FormData(form);return {vehicle_id:String(f.get('vehicle_id')||''),status:String(f.get('status')||'DRAFT'),caption:String(f.get('caption')||''),media_url:String(f.get('media_url')||''),scheduled_at:f.get('scheduled_at')?new Date(String(f.get('scheduled_at'))).toISOString():null,notes:String(f.get('notes')||'')}}
function enhanceForm(){const form=$('#igForm');if(!form)return;const status=form.elements.status;if(status){const published=[...status.options].find(o=>o.value==='PUBLISHED');if(published&&!published.selected)published.disabled=true}let note=$('#igQuality');if(!note){note=document.createElement('div');note.id='igQuality';note.className='ig-quality';const actions=form.querySelector('.ig-actions');actions?form.insertBefore(note,actions):form.appendChild(note)}const h=instagramContentHealth(formCandidate(form));note.classList.toggle('ok',h.blocking.length===0);note.textContent=h.blocking.length?`Da sistemare: ${h.blocking.map(label).join(', ')}.`:'Contenuto coerente. Se lo programmi, resterà in coda finché il server Meta non confermerà la pubblicazione.'}
function enhance(){if(typeof document==='undefined')return;injectStyle();renderHealth();enhanceForm()}
function schedule(){if(queued)return;queued=true;setTimeout(()=>{queued=false;enhance()},30)}

if(typeof document!=='undefined'){
  document.addEventListener('change',e=>{const form=e.target?.closest?.('#igForm');if(!form)return;if(e.target?.name==='status'&&e.target.value==='PUBLISHED'){e.target.value='READY';alert('PUBBLICATO viene impostato solo dopo conferma Meta/server.');}enhanceForm()},true);
  document.addEventListener('input',e=>{if(e.target?.closest?.('#igForm'))enhanceForm()},true);
  document.addEventListener('submit',e=>{const form=e.target;if(form?.id!=='igForm')return;const c=formCandidate(form),raw=String(c.media_url||'').trim();if(raw&&!normalizePublicMediaUrl(raw)){e.preventDefault();e.stopImmediatePropagation();alert('Il media deve avere un URL HTTPS pubblico valido.');return}if(c.status==='PUBLISHED'){e.preventDefault();e.stopImmediatePropagation();alert('PUBBLICATO non può essere impostato manualmente: serve conferma Meta/server.');return}const h=instagramContentHealth(c);if(h.blocking.length){e.preventDefault();e.stopImmediatePropagation();alert(`Contenuto non pronto: ${h.blocking.map(label).join(', ')}.`)}},true);
  const observer=new MutationObserver(schedule);observer.observe(document.documentElement,{subtree:true,childList:true});
  window.addEventListener('dealer:session',()=>load().catch(()=>{}));window.addEventListener('dealer:data-updated',()=>load().catch(()=>{}));window.addEventListener('online',()=>load().catch(()=>{}));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>load().catch(()=>{}));else load().catch(()=>{});
}
