import {OfflineDB} from './offline.js';
import {Session} from './api.js';
import {buildReportRows,reportTotals,periodMatches,canViewFinancialReports,openInvoiceAmount,isInvoiceOverdue} from './report-metrics.js?v=1.6.5';

const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n||0));
const num=n=>new Intl.NumberFormat('it-IT').format(Number(n||0));
const cfg=()=>window.DEALER_CONFIG||{};const dealer=()=>Session.get()?.dealer||{};const dealerId=()=>dealer().id||'demo-malu23';
const dealerName=()=>dealer().display_name||dealer().name||dealer().slug||'Concessionaria';
const dealerSlug=()=>String(dealer().slug||dealerName()).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'concessionaria';
const state={dealerId:null,vehicles:[],financials:[],costs:[],invoices:[],contracts:[],period:'MONTH',mode:'EXECUTIVE',query:''};
const labels={STOCK:'Stock',PIPELINE:'Vendita in corso',DELIVERED:'Consegnata'};
function canUse(){return canViewFinancialReports(Session.get()?.profile||{},cfg().demoMode)}
function dataRows(now=new Date()){return buildReportRows(state,now).filter(r=>!state.query||[r.vehicle.brand,r.vehicle.model,r.vehicle.version,r.vehicle.plate,r.vehicle.vin].join(' ').toLowerCase().includes(state.query))}
async function load(){state.dealerId=dealerId();[state.vehicles,state.financials,state.costs,state.invoices,state.contracts]=await Promise.all([OfflineDB.list('vehicles',state.dealerId),OfflineDB.list('vehicle_financials',state.dealerId),OfflineDB.list('vehicle_costs',state.dealerId),OfflineDB.list('invoices',state.dealerId),OfflineDB.list('contracts',state.dealerId)]);render()}
function injectUi(){
 if(!$('#reportsV14Style')){const s=document.createElement('style');s.id='reportsV14Style';s.textContent=`body .mobile-nav{grid-template-columns:repeat(13,minmax(68px,1fr))!important;overflow-x:auto}.rep-kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin-bottom:12px}.rep-kpis>div,.rep-panel{background:#fff;border:1px solid var(--line);border-radius:14px;padding:12px}.rep-kpis span,.rep-panel span{display:block;font-size:7px;color:var(--muted);font-weight:900}.rep-kpis b{display:block;font-size:15px;margin-top:4px}.rep-tools{display:grid;grid-template-columns:1fr 180px 220px auto auto;gap:8px;margin-bottom:12px}.rep-tools input,.rep-tools select{border:1px solid var(--line);background:#fff;border-radius:11px;padding:10px 11px;font-size:10px}.rep-table{background:#fff;border:1px solid var(--line);border-radius:16px;overflow:auto}.rep-head,.rep-row{display:grid;grid-template-columns:minmax(190px,1.4fr) minmax(105px,.7fr) repeat(6,minmax(90px,.7fr));gap:8px;align-items:center;padding:10px 12px;min-width:1020px}.rep-head{background:#f3f4f6;font-size:7px;font-weight:1000;color:var(--muted)}.rep-row{border-top:1px solid var(--line);font-size:9px}.rep-row strong{font-size:10px}.rep-row small{display:block;color:var(--muted);font-size:7px;margin-top:2px}.rep-age{font-weight:1000}.rep-age.warn{color:#b66a18}.rep-age.bad{color:#b42318}.rep-pos{color:#18794e}.rep-neg{color:#b42318}.rep-pipeline{color:#6b4d08}.rep-note{margin-top:10px;font-size:8px;color:var(--muted);line-height:1.55}.rep-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}.rep-summary .rep-panel b{font-size:16px;display:block;margin-top:5px}.rep-title-print{display:none}@media(max-width:1000px){.rep-kpis{grid-template-columns:1fr 1fr 1fr}.rep-tools{grid-template-columns:1fr 1fr}.rep-summary{grid-template-columns:1fr 1fr}}@media(max-width:700px){.rep-kpis,.rep-summary{grid-template-columns:1fr 1fr}.rep-tools{grid-template-columns:1fr}}@media print{body{background:#fff!important}.side,.top,.mobile-nav,.telegram-banner,.syncbar,.rep-tools,.section{display:none!important}.main,.content{padding:0!important;max-width:none!important}.view{display:none!important}.view[data-view="report"].active{display:block!important}.rep-title-print{display:block;margin:0 0 14px}.rep-title-print h1{font-size:20px;margin:0}.rep-title-print p{font-size:9px;color:#555}.rep-kpis{grid-template-columns:repeat(3,1fr);break-inside:avoid}.rep-kpis>div,.rep-panel,.rep-table{box-shadow:none!important;border-color:#cfd3d8!important}.rep-table{overflow:visible}.rep-head,.rep-row{min-width:0;grid-template-columns:1.3fr .8fr repeat(6,.7fr);font-size:6.5px}.rep-row strong{font-size:7.5px}.rep-note{font-size:7px}@page{size:A4 landscape;margin:12mm}}`;document.head.appendChild(s)}
 const side=$('.side .nav');if(side&&!side.querySelector('[data-view="report"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.view='report';b.innerHTML='▤ &nbsp; Report';side.insertBefore(b,side.querySelector('[data-view="admin"]'))}
 const mobile=$('.mobile-nav');if(mobile&&!mobile.querySelector('[data-view="report"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.view='report';b.innerHTML='▤<small>REPORT</small>';mobile.insertBefore(b,mobile.querySelector('[data-view="admin"]'))}
 const content=$('.content');if(content&&!content.querySelector('[data-view="report"]')){const s=document.createElement('section');s.className='view';s.dataset.view='report';s.innerHTML='<div class="section"><div><small>REPORT V1.4</small><h2>Report concessionaria</h2></div></div><div class="rep-title-print"><h1 id="repPrintTitle"></h1><p id="repPrintMeta"></p></div><div id="reportsApp"></div>';content.insertBefore(s,content.querySelector('[data-view="admin"]'))}
 $$('[data-view="report"].navbtn').forEach(b=>b.addEventListener('click',openView));
}
function openView(){if(!canUse()){alert('I report economici sono riservati ad amministrazione/finanze.');return}$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view==='report'));$$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view==='report'));if($('#pageTitle'))$('#pageTitle').textContent='REPORT';window.scrollTo({top:0,behavior:'smooth'});load().catch(console.warn)}
function periodLabel(){return state.period==='MONTH'?'Mese corrente':state.period==='YEAR'?'Anno corrente':'Tutto'}
function render(){const root=$('#reportsApp');if(!root)return;const now=new Date(),all=dataRows(now),tot=reportTotals(all,state.invoices,state.period,now);root.innerHTML=`<div class="rep-kpis"><div><span>AUTO STOCK</span><b>${tot.stockCount}</b></div><div><span>VENDITE IN CORSO</span><b>${tot.pipelineCount}</b></div><div><span>CAPITALE INVESTITO</span><b>${money(tot.activeCapital)}</b></div><div><span>VENDUTO CONSEGNATO</span><b>${money(tot.revenue)}</b></div><div><span>MARGINE CONSEGNATO</span><b class="${tot.margin<0?'rep-neg':'rep-pos'}">${money(tot.margin)}</b></div><div><span>DA INCASSARE</span><b>${money(tot.receivables)}</b></div></div><div class="rep-summary"><div class="rep-panel"><span>SCADUTO DA INCASSARE</span><b class="${tot.overdue>0?'rep-neg':''}">${money(tot.overdue)}</b></div><div class="rep-panel"><span>AGEING STOCK</span><b>${tot.aged60} auto oltre 60 giorni</b></div><div class="rep-panel"><span>MEDIA STOCK</span><b>${tot.averageStockDays} giorni</b></div><div class="rep-panel"><span>CONSEGNE NEL PERIODO</span><b>${tot.deliveredCount}</b></div></div><div class="rep-tools"><input id="repSearch" value="${esc(state.query)}" placeholder="Cerca auto, targa, telaio…"><select id="repPeriod"><option value="MONTH" ${state.period==='MONTH'?'selected':''}>Mese corrente</option><option value="YEAR" ${state.period==='YEAR'?'selected':''}>Anno corrente</option><option value="ALL" ${state.period==='ALL'?'selected':''}>Tutto</option></select><select id="repMode"><option value="EXECUTIVE" ${state.mode==='EXECUTIVE'?'selected':''}>Riepilogo completo</option><option value="STOCK" ${state.mode==='STOCK'?'selected':''}>Stock + spese</option><option value="PIPELINE" ${state.mode==='PIPELINE'?'selected':''}>Vendite in corso</option><option value="SALES" ${state.mode==='SALES'?'selected':''}>Vendite + margini</option><option value="AGEING" ${state.mode==='AGEING'?'selected':''}>Ageing stock</option></select><button class="btn ghost" id="repCsv">Esporta CSV</button><button class="btn" id="repPrint">Stampa / PDF</button></div><div class="rep-table"><div class="rep-head"><div>AUTO</div><div>STATO</div><div>GIORNI</div><div>ACQUISTO</div><div>SPESE</div><div>COSTO REALE</div><div>VENDITA</div><div>MARGINE</div></div><div id="repRows"></div></div><div class="rep-note"><b>Regola contabile gestionale:</b> ricavo e margine entrano nel report solo quando la vendita risulta consegnata. Le vendite in corso mostrano il prezzo concordato ma non aumentano ricavi/margini. Il margine è gestionale lordo (vendita − acquisto − spese veicolo), non utile fiscale: IVA, imposte e costi generali restano esclusi. Layout di stampa: A4 landscape.</div>`;$('#repSearch').oninput=e=>{state.query=e.target.value.toLowerCase();renderRows()};$('#repPeriod').onchange=e=>{state.period=e.target.value;render()};$('#repMode').onchange=e=>{state.mode=e.target.value;renderRows()};$('#repCsv').onclick=exportCsv;$('#repPrint').onclick=printReport;renderRows()}
function filtered(){const now=new Date();let list=dataRows(now);if(state.mode==='STOCK')list=list.filter(r=>r.state==='STOCK');if(state.mode==='PIPELINE')list=list.filter(r=>r.state==='PIPELINE');if(state.mode==='SALES')list=list.filter(r=>r.state==='DELIVERED'&&periodMatches(r.saleDate,state.period,now));if(state.mode==='AGEING')list=list.filter(r=>r.state==='STOCK'&&r.stockDays>=30).sort((a,b)=>b.stockDays-a.stockDays);if(state.mode==='EXECUTIVE')list=list.sort((a,b)=>({PIPELINE:0,STOCK:1,DELIVERED:2}[a.state]-({PIPELINE:0,STOCK:1,DELIVERED:2}[b.state]))||b.stockDays-a.stockDays);return list}
function renderRows(){const root=$('#repRows');if(!root)return;const list=filtered();root.innerHTML=list.length?list.map(r=>{const shownSale=r.state==='DELIVERED'?r.recognizedSale:r.state==='PIPELINE'?r.agreedSale:0;return `<div class="rep-row"><div><strong>${esc(`${r.vehicle.brand||''} ${r.vehicle.model||''} ${r.vehicle.version||''}`.trim())}</strong><small>${esc(r.vehicle.plate||r.vehicle.vin||'—')}${r.saleDate?` · consegna ${esc(r.saleDate)}`:''}</small></div><div><strong class="${r.state==='PIPELINE'?'rep-pipeline':''}">${esc(labels[r.state]||r.state)}</strong></div><div><span class="rep-age ${r.stockDays>=90?'bad':r.stockDays>=60?'warn':''}">${r.state==='DELIVERED'?'—':`${num(r.stockDays)} gg`}</span></div><div>${money(r.purchase)}</div><div>${money(r.expenses)}</div><div><strong>${money(r.realCost)}</strong></div><div>${shownSale?money(shownSale):'—'}</div><div><strong class="${r.margin!==null?(r.margin<0?'rep-neg':'rep-pos'):''}">${r.margin!==null?money(r.margin):'—'}</strong></div></div>`}).join(''):'<div class="empty" style="margin:12px">Nessun dato per questo report.</div>'}
function printReport(){if($('#repPrintTitle'))$('#repPrintTitle').textContent=`${dealerName()} — Report gestionale`;if($('#repPrintMeta'))$('#repPrintMeta').textContent=`Generato ${new Date().toLocaleString('it-IT')} · ${periodLabel()} · ${state.mode}`;window.print()}
function exportCsv(){const list=filtered(),lines=[['Concessionaria','Marca','Modello','Versione','Targa','VIN','Stato','Data consegna','Giorni stock','Acquisto','Spese','Costo reale','Vendita concordata','Vendita riconosciuta','Margine gestionale','Regime IVA'].join(';')];for(const r of list)lines.push([dealerName(),r.vehicle.brand,r.vehicle.model,r.vehicle.version,r.vehicle.plate,r.vehicle.vin,labels[r.state]||r.state,r.saleDate,r.state==='DELIVERED'?'':r.stockDays,r.purchase,r.expenses,r.realCost,r.agreedSale||'',r.recognizedSale||'',r.margin??'',r.invoice?.vat_regime||r.invoice?.vat_regime_code||''].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';'));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${dealerSlug()}-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.addEventListener('dealer:data-updated',()=>load().catch(()=>{}));
injectUi();
