import {VERSION,APP_VERSION,scan,fixtures,decisionModel,COST_KEYS,COST_LABELS,DEEP_FIELDS,DEEP_LABELS} from './core.mjs?v=2.1.1';
const $=id=>document.getElementById(id);let cars=[],filter='shortlist',selected=null,connected=false,currentDecision=null;
const money=n=>n===null||n===undefined?'—':new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n);const pct=n=>n===null||n===undefined?'—':new Intl.NumberFormat('it-IT',{maximumFractionDigits:1}).format(n)+'%';
const numeric=id=>$(id).value.trim()===''?null:Number($(id).value);const setStep=(id,state)=>{$(id).dataset.state=state||''};
function buildCosts(){const grid=$('costGrid');for(const key of COST_KEYS){const label=document.createElement('label');label.textContent=COST_LABELS[key];const input=document.createElement('input');input.id='cost-'+key;input.type='number';input.min='0';input.step='0.01';input.inputMode='decimal';label.append(input);grid.append(label)}}
buildCosts();
function evidence(){const grid=$('evidenceGrid');grid.replaceChildren();if(!selected){$('deepState').textContent='—';return}let known=0;for(const key of DEEP_FIELDS){const item=document.createElement('div');const k=document.createElement('span');k.textContent=DEEP_LABELS[key];const v=document.createElement('strong');const value=selected[key];if(value!==null&&value!==undefined&&value!==''){known++;v.textContent=String(value)}else{v.textContent='UNKNOWN';v.className='unknown'}item.append(k,v);grid.append(item)}$('deepState').textContent=known===DEEP_FIELDS.length?'Completo':known+'/'+DEEP_FIELDS.length+' verificati';setStep('step-deep',known===DEEP_FIELDS.length?'ok':'review')}
function inputs(){return {currentBid:numeric('currentBid'),resale:numeric('resale'),desiredMargin:numeric('margin'),comparables:[numeric('comp1'),numeric('comp2'),numeric('comp3')],costs:Object.fromEntries(COST_KEYS.map(k=>[k,numeric('cost-'+k)]))}}
function budget(){currentDecision=decisionModel(selected,inputs());const d=currentDecision;$('marketMedian').textContent=money(d.market.median);$('costTotal').textContent=money(d.costTotal);$('landedCost').textContent=money(d.landedCost);$('projectedMargin').textContent=money(d.projectedMargin);$('roi').textContent=pct(d.roi);$('maxbid').textContent=money(d.maxBid);$('marketState').textContent=d.market.complete?d.market.count+' comparabili':'Servono 3 comparabili';$('costState').textContent=d.costUnknown.length?'Mancano '+d.costUnknown.length:'Completo';setStep('step-market',d.market.complete?'ok':'review');setStep('step-cost',d.costUnknown.length?'review':'ok');setStep('step-decision',d.verified?'ok':d.complete||d.maxBid!==null?'review':'');$('report').disabled=!d.complete;
 if(d.withinMax===true){$('bidGate').textContent='Prezzo corrente entro il MAX BID';$('bidGate').className='good'}else if(d.withinMax===false){$('bidGate').textContent='Prezzo corrente oltre il MAX BID';$('bidGate').className='bad'}else{$('bidGate').textContent='Completa i dati per la decisione.';$('bidGate').className=''}
 const missing=[];if(!selected)missing.push('veicolo');if(!d.market.complete)missing.push('3 comparabili');if(d.costUnknown.length)missing.push('costi: '+d.costUnknown.map(k=>COST_LABELS[k]).join(', '));if(d.currentBid===null)missing.push('prezzo corrente');if(d.resale===null)missing.push('rivendita');if(d.desiredMargin===null)missing.push('margine obiettivo');if(missing.length)$('budgetState').textContent='Da completare: '+missing.join(' · ');else if(!d.deep.complete)$('budgetState').textContent='Calcolo decisionale completo · deep analysis incompleta: i campi mancanti resteranno UNKNOWN nel report.';else $('budgetState').textContent='Pipeline decisionale verificata · pronta per il report.'}
function render(){for(const status of ['shortlist','review','excluded'])$('n-'+status).textContent=cars.filter(c=>c.status===status).length;const container=$('cars');container.replaceChildren();const visible=cars.filter(c=>c.status===filter);if(!visible.length){const p=document.createElement('div');p.className='empty';p.textContent='Nessun veicolo in questa sezione.';container.append(p)}for(const car of visible){const card=document.createElement('article');card.className='vehicle'+(selected===car?' selected':'');const meta=document.createElement('div');meta.className='meta';meta.textContent=(car.id||'ID SCONOSCIUTO')+' / '+({shortlist:'IDONEO',review:'DA VERIFICARE',excluded:'ESCLUSO'}[car.status]);const title=document.createElement('h3');title.textContent=car.name||'Veicolo senza nome';const details=document.createElement('p');details.textContent=(car.km===null||car.km===undefined?'Km sconosciuti':car.km.toLocaleString('it-IT')+' km')+' · '+(car.registered||'Immatricolazione sconosciuta');card.append(meta,title,details);if(car.reasons.length){const reason=document.createElement('p');reason.className='reason';reason.textContent=car.reasons.join(' · ');card.append(reason)}if(car.status==='shortlist'){const button=document.createElement('button');button.textContent=selected===car?'Selezionato':'Analizza →';button.onclick=()=>selectCar(car);card.append(button)}container.append(card)}}
function clearInputs(){for(const id of ['currentBid','resale','margin','comp1','comp2','comp3'])$(id).value='';for(const k of COST_KEYS)$('cost-'+k).value=''}
function selectCar(car){selected=car;$('selected').textContent=car.name;clearInputs();if(car.currentBid!==null&&car.currentBid!==undefined)$('currentBid').value=car.currentBid;if(car.demoDecision){car.demoDecision.comparables.forEach((v,i)=>$('comp'+(i+1)).value=v);for(const [k,v] of Object.entries(car.demoDecision.costs||{}))if($('cost-'+k))$('cost-'+k).value=v;$('margin').value=car.demoDecision.desiredMargin??''}evidence();budget();render()}
function load(rows,source){const result=scan(rows);cars=result.cars;selected=null;clearInputs();$('selected').textContent='Seleziona un veicolo dalla shortlist.';$('source').textContent=source;$('summary').textContent=rows.length+' record · '+cars.length+' veicoli · '+result.duplicates+' duplicati rimossi';setStep('step-scan','ok');setStep('step-shortlist',cars.some(c=>c.status==='shortlist')?'ok':'review');for(const id of ['step-deep','step-cost','step-market','step-decision','step-report'])setStep(id,'');evidence();budget();render();if(source.startsWith('DEMO')){const first=cars.find(c=>c.status==='shortlist');if(first)selectCar(first)}}
$('demo').onclick=()=>load(fixtures,'DEMO · DATI FITTIZI · E2E');document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));render()});$('budget').onsubmit=e=>e.preventDefault();$('budget').oninput=budget;
function addLine(parent,name,value,strong=false){const row=document.createElement('div');const a=document.createElement('span');const b=document.createElement(strong?'b':'strong');a.textContent=name;b.textContent=value;row.append(a,b);parent.append(row)}
$('report').onclick=async()=>{const d=currentDecision;if(!d?.complete||!selected)return;const report=$('reportSheet');report.replaceChildren();const brand=document.createElement('div');brand.className='report-brand';brand.textContent='AUTOBID / REPORT DECISIONALE · '+APP_VERSION;const h=document.createElement('h2');h.textContent=selected.name;const meta=document.createElement('p');meta.className='report-meta';meta.textContent=(selected.id||'ID UNKNOWN')+' · '+(selected.km?.toLocaleString('it-IT')||'Km UNKNOWN')+' km · '+(selected.registered||'Data UNKNOWN');const deep=document.createElement('div');deep.className='report-lines';for(const key of DEEP_FIELDS)addLine(deep,DEEP_LABELS[key],String(selected[key]??'UNKNOWN'));const lines=document.createElement('div');lines.className='report-lines';addLine(lines,'Mediana mercato Italia',money(d.market.median));addLine(lines,'Prezzo / offerta corrente',money(d.currentBid));addLine(lines,'Costi totali',money(d.costTotal));addLine(lines,'Costo landed',money(d.landedCost));addLine(lines,'Rivendita prevista',money(d.resale));addLine(lines,'Margine previsto',money(d.projectedMargin));addLine(lines,'ROI',pct(d.roi));addLine(lines,'Margine obiettivo',money(d.desiredMargin));addLine(lines,'MAX BID',money(d.maxBid),true);const gate=document.createElement('p');gate.className='report-gate '+(d.withinMax?'good':'bad');gate.textContent=d.withinMax?'ENTRO MAX BID':'OLTRE MAX BID';const note=document.createElement('p');note.className='report-note';note.textContent='Stima decisionale. Verificare dati AutoProff, IVA, danni, documenti e condizioni prima dell’acquisto. AutoBid non invia offerte.';report.append(brand,h,meta,deep,lines,gate,note);report.hidden=false;$('printReport').hidden=false;setStep('step-report','ok');await saveHistory({id:crypto.randomUUID(),createdAt:new Date().toISOString(),vehicle:selected.name,vehicleId:selected.id,vin:selected.vin||null,maxBid:d.maxBid,currentBid:d.currentBid,projectedMargin:d.projectedMargin,roi:d.roi,withinMax:d.withinMax});await renderHistory();report.scrollIntoView({behavior:'smooth',block:'start'})};$('printReport').onclick=()=>print();
function state(title,detail,ready=false){$('connection').textContent=title;$('detail').textContent=detail;connected=ready;$('live').disabled=!ready}
async function request(type){const id=$('extensionId').value.trim();if(!/^[a-p]{32}$/.test(id))throw Error('ID estensione non valido: usa le 32 lettere mostrate in chrome://extensions.');if(!globalThis.chrome?.runtime?.sendMessage)throw Error('Apri in Chrome desktop e installa l’estensione AutoBid.');return new Promise((resolve,reject)=>{const requestId=crypto.randomUUID();const timer=setTimeout(()=>reject(Error('EXTENSION_TIMEOUT: estensione non raggiungibile.')),7000);chrome.runtime.sendMessage(id,{type,protocol:1,version:VERSION,requestId},response=>{clearTimeout(timer);if(chrome.runtime.lastError)return reject(Error('CHROME_RUNTIME: '+chrome.runtime.lastError.message));if(!response||response.requestId!==requestId||response.protocol!==1)return reject(Error('PROTOCOL_ERROR: risposta non valida.'));if(response.error)return reject(Error(response.error));if(response.version!==VERSION)return reject(Error('VERSION_MISMATCH: aggiorna PWA ed estensione a '+VERSION));resolve(response)})})}
$('connect').onclick=async()=>{state('Collegamento…','Verifica versione e protocollo.');try{const r=await request('AUTOBID_HELLO');state('Collegata · '+r.version,'AutoProff: '+(r.autoProffTabs?'scheda rilevata':'apri una scheda e accedi')+'.',true)}catch(e){state('Connessione non riuscita',e.message)}};$('live').onclick=async()=>{if(!connected)return;$('live').disabled=true;try{const r=await request('AUTOBID_SCAN');if(!Array.isArray(r.rows)||r.rows.length>5000)throw Error('PAYLOAD_INVALID: risultati scanner non validi.');load(r.rows,'AUTOPROFF · LETTURA ESTENSIONE');state('Collegata · '+VERSION,r.rows.length+' record ricevuti.',true)}catch(e){state('Scansione non riuscita',e.message,false)}};
function openDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in globalThis))return reject(Error('IndexedDB non disponibile'));const req=indexedDB.open('autobid-local',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('analyses'))req.result.createObjectStore('analyses',{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function saveHistory(item){try{const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction('analyses','readwrite');tx.objectStore('analyses').put(item);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch(e){$('historyState').textContent='Storico non disponibile'}}
async function readHistory(){const db=await openDb();const rows=await new Promise((resolve,reject)=>{const tx=db.transaction('analyses','readonly');const req=tx.objectStore('analyses').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();return rows.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,20)}
async function renderHistory(){const list=$('historyList');try{const rows=await readHistory();list.replaceChildren();$('historyState').textContent=rows.length+' salvate · locale';if(!rows.length){const p=document.createElement('p');p.className='hint';p.textContent='Nessuna analisi salvata.';list.append(p);return}for(const row of rows){const item=document.createElement('article');const h=document.createElement('strong');h.textContent=row.vehicle;const p=document.createElement('p');p.textContent=new Date(row.createdAt).toLocaleString('it-IT')+' · MAX BID '+money(row.maxBid)+' · margine '+money(row.projectedMargin)+' · ROI '+pct(row.roi);const badge=document.createElement('span');badge.className=row.withinMax?'good':'bad';badge.textContent=row.withinMax?'ENTRO MAX':'OLTRE MAX';item.append(h,p,badge);list.append(item)}}catch(e){$('historyState').textContent='Storico non disponibile'}}
budget();renderHistory();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
