import vm from 'node:vm';
import fs from 'node:fs';
import assert from 'node:assert/strict';
let handler;
let tabs=[];
const chrome={runtime:{onMessageExternal:{addListener(fn){handler=fn}}},tabs:{query:async()=>tabs},scripting:{executeScript:async()=>[{result:[{id:'sample',km:null,accident:null}]}]}};
vm.runInNewContext(fs.readFileSync(new URL('./extension/background.js',import.meta.url),'utf8'),{chrome,URL});
const sender={url:'https://webinsolito.github.io/webinsolito/autobid/'};
const message={type:'AUTOBID_HELLO',version:'2.1.0',protocol:1,requestId:'test'};
const call=(m=message,s=sender)=>new Promise(resolve=>handler(m,s,resolve));
assert.equal((await call()).state,'ready');\nassert.equal((await call()).autoProffTabs,0);
assert.equal((await call()).requestId,'test');
assert.match((await call({...message,version:'1.0.0'})).error,/VERSION_MISMATCH/);
assert.equal(handler(message,{url:'https://untrusted.example/'},()=>assert.fail()),false);
assert.equal(handler(message,{url:'https://webinsolito.github.io/other/'},()=>assert.fail()),false);
assert.match((await call({...message,type:'AUTOBID_SCAN'})).error,/AUTOPROFF_NOT_OPEN/);
tabs=[{id:1,active:true}];
assert.equal((await call({...message,type:'AUTOBID_SCAN'})).rows[0].km,null);
console.log('PASS: connector mocked handshake, origin/path, version, missing tab, unknown transport');
