(() => {
  'use strict';
  const DB_NAME='herbarium.local.v1', STORE_NAME='observations', MAX_IMAGE_EDGE=1600, JPEG_QUALITY=0.78, MAX_INPUT_BYTES=12*1024*1024;
  // Reserved contract for a future validated local classifier. These labels are never inferred from filenames or metadata.
  const NEGATIVE_CATEGORIES=new Set(['object','animal','print','tablecloth']);
  const classifyNegativeEvidence=signal=>NEGATIVE_CATEGORIES.has(signal)?{status:'REJECT',negativeCategory:signal}:{status:'UNKNOWN',negativeCategory:null};
  const inputs=[...document.querySelectorAll('input[type=file]')], analyse=document.getElementById('analyse'), result=document.getElementById('result'), observationCount=document.getElementById('observationCount'), speciesCount=document.getElementById('speciesCount');
  const openDb=()=>new Promise((resolve,reject)=>{if(!('indexedDB' in window))return reject(new Error('IndexedDB non disponibile.'));const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE_NAME))db.createObjectStore(STORE_NAME,{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('Database locale non disponibile.'));});
  const countObservations=async()=>{const db=await openDb();try{return await new Promise((resolve,reject)=>{const request=db.transaction(STORE_NAME,'readonly').objectStore(STORE_NAME).count();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}finally{db.close();}};
  const loadObservations=async()=>{const db=await openDb();try{return await new Promise((resolve,reject)=>{const request=db.transaction(STORE_NAME,'readonly').objectStore(STORE_NAME).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('Lettura osservazioni locali fallita.'));});}finally{db.close();}};
  const saveObservation=async observation=>{const db=await openDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(STORE_NAME,'readwrite');tx.objectStore(STORE_NAME).add(observation);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||new Error('Salvataggio locale fallito.'));tx.onabort=()=>reject(tx.error||new Error('Salvataggio locale annullato.'));});}finally{db.close();}};
  const renderStats=async()=>{try{observationCount.textContent=String(await countObservations());}catch{observationCount.textContent='—';}speciesCount.textContent='0';};
  const renderCollection=async()=>{const list=document.getElementById('collectionList'),count=document.getElementById('collectionCount'),verifiedCount=document.getElementById('collectionVerifiedCount');if(!list)return;try{const observations=(await loadObservations()).filter(item=>item&&item.status==='UNKNOWN').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));count.textContent=String(observations.length);verifiedCount.textContent='0';list.replaceChildren();if(!observations.length){const empty=document.createElement('p');empty.className='empty-state';empty.textContent='Nessuna osservazione reale salvata. La raccolta resta vuota finché non aggiungi prove fotografiche.';list.append(empty);return;}observations.forEach((item,index)=>{const card=document.createElement('article');card.className='pending-card';const title=document.createElement('strong');title.textContent=`Osservazione ${String(index+1).padStart(2,'0')} · UNKNOWN`;const meta=document.createElement('span');const roles=Array.isArray(item.roles)?item.roles.length:0;const date=item.createdAt?new Date(item.createdAt).toLocaleString('it-IT'):'data non disponibile';meta.textContent=`${roles} vista/e · ${date} · solo dati locali`;card.append(title,meta);list.append(card);});}catch{count.textContent='—';verifiedCount.textContent='0';list.replaceChildren();const error=document.createElement('p');error.className='empty-state';error.textContent='Impossibile leggere la raccolta locale. Nessun dato è stato modificato.';list.append(error);}};
  const renderBook=async()=>{const list=document.getElementById('pendingList'),count=document.getElementById('pendingCount'),bookCount=document.getElementById('bookCount');if(!list)return;try{const observations=(await loadObservations()).filter(item=>item&&item.status==='UNKNOWN').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));count.textContent=String(observations.length);bookCount.textContent=`${observations.length} osservazioni`;list.replaceChildren();if(!observations.length){const empty=document.createElement('p');empty.className='empty-state';empty.textContent='Nessuna osservazione locale salvata. Il volume resta vuoto finché non raccogli prove reali.';list.append(empty);return;}observations.forEach((item,index)=>{const card=document.createElement('article');card.className='pending-card';const title=document.createElement('strong');title.textContent=`Specimen ${String(index+1).padStart(2,'0')} · UNKNOWN`;const meta=document.createElement('span');const roles=Array.isArray(item.roles)?item.roles.length:0;const date=item.createdAt?new Date(item.createdAt).toLocaleString('it-IT'):'data non disponibile';meta.textContent=`${roles} vista/e · ${date} · conservato localmente`;card.append(title,meta);list.append(card);});}catch{count.textContent='—';bookCount.textContent='Dati locali non disponibili';list.replaceChildren();const error=document.createElement('p');error.className='empty-state';error.textContent='Impossibile leggere il volume locale. Nessun dato è stato modificato.';list.append(error);}};
  const renderAtlas=async()=>{const locatedCount=document.getElementById('atlasLocatedCount'),regionCount=document.getElementById('atlasRegionCount'),regionsEl=document.getElementById('atlasRegions');if(!regionsEl)return;try{const observations=await loadObservations();const located=observations.filter(item=>item&&item.location&&Number.isFinite(item.location.latitude)&&Number.isFinite(item.location.longitude));const regionNames=[...new Set(observations.map(item=>typeof item.region==='string'?item.region.trim():'').filter(Boolean))].sort((a,b)=>a.localeCompare(b,'it'));locatedCount.textContent=String(located.length);regionCount.textContent=String(regionNames.length);regionsEl.replaceChildren();if(!located.length&&!regionNames.length){const empty=document.createElement('p');empty.className='empty-state';empty.textContent='Nessuna osservazione contiene ancora una posizione o una regione reale. L’atlante resta vuoto.';regionsEl.append(empty);return;}regionNames.forEach(name=>{const chip=document.createElement('span');chip.className='atlas-region-chip';chip.textContent=name;regionsEl.append(chip);});if(!regionNames.length){const note=document.createElement('p');note.className='empty-state';note.textContent=`${located.length} osservazione/i hanno coordinate locali, ma nessuna regione testuale è stata salvata.`;regionsEl.append(note);}}catch{locatedCount.textContent='—';regionCount.textContent='—';regionsEl.replaceChildren();const error=document.createElement('p');error.className='empty-state';error.textContent='Impossibile leggere l’atlante locale. Nessun dato è stato modificato.';regionsEl.append(error);}};
  const renderAcademy=async()=>{const list=document.getElementById('academyList'),count=document.getElementById('academyObservationCount'),multiCount=document.getElementById('academyMultiViewCount');if(!list)return;try{const observations=(await loadObservations()).filter(item=>item&&item.status==='UNKNOWN').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const multi=observations.filter(item=>Array.isArray(item.roles)&&item.roles.length>=2);count.textContent=String(observations.length);multiCount.textContent=String(multi.length);list.replaceChildren();if(!observations.length){const empty=document.createElement('p');empty.className='empty-state';empty.textContent='Nessuna osservazione reale disponibile. L’Academy resta vuota finché non raccogli prove sul campo.';list.append(empty);return;}observations.forEach((item,index)=>{const roles=Array.isArray(item.roles)?item.roles:[];const card=document.createElement('article');card.className='pending-card';const title=document.createElement('strong');title.textContent=`Esercizio ${String(index+1).padStart(2,'0')} · osservazione UNKNOWN`;const meta=document.createElement('span');meta.textContent=roles.length>=2?`${roles.length} viste reali · confronta forma generale e dettagli prima di qualsiasi determinazione.`:`${roles.length} vista reale · aggiungi almeno una seconda vista per documentare meglio l’esemplare.`;card.append(title,meta);list.append(card);});}catch{count.textContent='—';multiCount.textContent='—';list.replaceChildren();const error=document.createElement('p');error.className='empty-state';error.textContent='Impossibile leggere i dati locali dell’Academy. Nessun dato è stato modificato.';list.append(error);}};
  const selectedInputs=()=>inputs.filter(input=>input.files&&input.files.length),setResult=message=>{result.textContent=message;};
  const update=()=>{const count=selectedInputs().length;analyse.disabled=count===0;setResult(count?`UNKNOWN — ${count} vista/e raccolte. Motore botanico validato non installato.`:'UNKNOWN — aggiungi almeno una foto.');};
  const fileToDataUrl=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error||new Error('Impossibile leggere la foto.'));reader.readAsDataURL(file);});
  const loadImage=dataUrl=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Impossibile decodificare la foto.'));image.src=dataUrl;});
  const canvasToBlob=canvas=>new Promise((resolve,reject)=>{canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Compressione foto fallita.')),'image/jpeg',JPEG_QUALITY);});
  const prepareEvidenceImage=async file=>{if(file.type&&!file.type.startsWith('image/'))throw new Error("Il file selezionato non è un'immagine.");if(file.size&&file.size>MAX_INPUT_BYTES)throw new Error('La foto selezionata supera il limite locale consentito.');const original=await fileToDataUrl(file),image=await loadImage(original),scale=Math.min(1,MAX_IMAGE_EDGE/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d');if(!context)throw new Error('Canvas non disponibile.');context.drawImage(image,0,0,width,height);return{blob:await canvasToBlob(canvas),width,height,originalBytes:file.size||null};};
  const validateSelection=()=>{for(const input of selectedInputs()){const file=input.files[0];if(file.type&&!file.type.startsWith('image/'))return "Il file selezionato non è un'immagine.";if(file.size&&file.size>MAX_INPUT_BYTES)return'La foto selezionata supera 12 MB: scegli una foto più leggera.';}return null;};
  inputs.forEach(input=>input.addEventListener('change',()=>{const error=validateSelection();if(error){analyse.disabled=true;setResult(`UNKNOWN — ${error} Nessun dato è stato salvato.`);return;}update();}));
  analyse.addEventListener('click',async()=>{const selected=selectedInputs();if(!selected.length)return;const selectionError=validateSelection();if(selectionError){analyse.disabled=true;setResult(`UNKNOWN — ${selectionError} Nessun dato è stato salvato.`);return;}analyse.disabled=true;setResult('Preparazione e salvataggio locale delle prove fotografiche…');try{const evidence=await Promise.all(selected.map(async input=>({role:input.id,name:input.files[0].name||null,type:'image/jpeg',...(await prepareEvidenceImage(input.files[0]))})));const negativeGate=classifyNegativeEvidence(null);await saveObservation({id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,createdAt:new Date().toISOString(),roles:evidence.map(item=>item.role),evidence,status:negativeGate.status,negativeCategory:negativeGate.negativeCategory});setResult('UNKNOWN — prove fotografiche ottimizzate e salvate nel database locale del dispositivo; nessuna identificazione automatica simulata.');await renderStats();await renderCollection();await renderBook();await renderAtlas();await renderAcademy();}catch(error){console.error(error);setResult('UNKNOWN — salvataggio locale non riuscito. Nessuna osservazione incompleta è stata registrata. Controlla lo spazio disponibile e riprova.');}finally{const selectionErrorAfterSave=validateSelection();if(selectionErrorAfterSave)analyse.disabled=true;else if(selectedInputs().length)analyse.disabled=false;}});
  document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(view=>view.classList.remove('active'));document.getElementById(button.dataset.view).classList.add('active');if(button.dataset.view==='collection')renderCollection();if(button.dataset.view==='book')renderBook();if(button.dataset.view==='atlas')renderAtlas();if(button.dataset.view==='academy')renderAcademy();}));
  const network=document.getElementById('network'),setNetwork=()=>{const online=navigator.onLine;network.textContent=online?'online · dati locali':'offline · dati locali';network.setAttribute('aria-label',online?'Connessione disponibile. Le osservazioni restano memorizzate localmente.':'Senza connessione. Le funzioni locali restano disponibili.');};addEventListener('online',setNetwork);addEventListener('offline',setNetwork);setNetwork();renderStats();renderCollection();renderBook();renderAtlas();renderAcademy();update();
})();
