(() => {
  'use strict';
  const DB_NAME='herbarium.local.v1', STORE_NAME='observations', MAX_IMAGE_EDGE=1600, JPEG_QUALITY=0.78, MAX_INPUT_BYTES=12*1024*1024;
  const NEGATIVE_CATEGORIES=new Set(['object','animal','print','tablecloth']);
  const classifyNegativeEvidence=signal=>NEGATIVE_CATEGORIES.has(signal)?{status:'REJECT',negativeCategory:signal}:{status:'UNKNOWN',negativeCategory:null};
  const byId=id=>document.getElementById(id);
  const inputs=[...document.querySelectorAll('input[type=file]')];
  const analyse=byId('analyse'), result=byId('result'), negativeSignal=byId('negativeSignal');

  const openDb=()=>new Promise((resolve,reject)=>{if(!('indexedDB' in window))return reject(new Error('IndexedDB non disponibile.'));const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE_NAME))db.createObjectStore(STORE_NAME,{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('Database locale non disponibile.'));});
  const loadObservations=async()=>{const db=await openDb();try{return await new Promise((resolve,reject)=>{const request=db.transaction(STORE_NAME,'readonly').objectStore(STORE_NAME).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('Lettura osservazioni locali fallita.'));});}finally{db.close();}};
  const countObservations=async()=>{const db=await openDb();try{return await new Promise((resolve,reject)=>{const request=db.transaction(STORE_NAME,'readonly').objectStore(STORE_NAME).count();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}finally{db.close();}};
  const saveObservation=async observation=>{const db=await openDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(STORE_NAME,'readwrite');tx.objectStore(STORE_NAME).add(observation);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||new Error('Salvataggio locale fallito.'));tx.onabort=()=>reject(tx.error||new Error('Salvataggio locale annullato.'));});}finally{db.close();}};
  const renderStats=async()=>{const observationCount=byId('observationCount'),speciesCount=byId('speciesCount');if(!observationCount&&!speciesCount)return;if(speciesCount)speciesCount.textContent='0';if(observationCount){try{observationCount.textContent=String(await countObservations());}catch{observationCount.textContent='—';}}};
  const observationImageUrl=item=>{const evidence=Array.isArray(item&&item.evidence)?item.evidence:[];const first=evidence.find(entry=>entry&&entry.blob instanceof Blob);return first?URL.createObjectURL(first.blob):null;};
  const friendlyDate=value=>{if(!value)return'Data non disponibile';try{return new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));}catch{return'Data non disponibile';}};
  const renderCollection=async()=>{const list=byId('collectionList'),count=byId('collectionCount'),verifiedCount=byId('collectionVerifiedCount');if(!list)return;try{const observations=(await loadObservations()).filter(item=>item&&item.status==='UNKNOWN').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));count.textContent=String(observations.length);verifiedCount.textContent='0';list.replaceChildren();if(!observations.length){const empty=document.createElement('div');empty.className='empty-state rich-empty';empty.innerHTML='<span class="empty-leaf" aria-hidden="true">⌁</span><strong>La tua raccolta è ancora vuota.</strong><span>La prima osservazione comparirà qui con la sua foto.</span><a href="./observe.html">Scatta la prima foto</a>';list.append(empty);return;}observations.forEach((item,index)=>{const card=document.createElement('article');card.className='observation-card';const media=document.createElement('div');media.className='observation-media';const imageUrl=observationImageUrl(item);if(imageUrl){const img=document.createElement('img');img.src=imageUrl;img.alt='Foto della tua osservazione';img.loading='lazy';media.append(img);}else{const placeholder=document.createElement('div');placeholder.className='observation-placeholder';placeholder.textContent='HERBARIUM';media.append(placeholder);}const body=document.createElement('div');body.className='observation-card-body';const top=document.createElement('div');top.className='observation-card-top';const badge=document.createElement('span');badge.className='human-status pending';badge.textContent='Da verificare';const number=document.createElement('span');number.className='observation-number';number.textContent=String(index+1).padStart(2,'0');top.append(badge,number);const title=document.createElement('h3');title.textContent='Osservazione botanica';const meta=document.createElement('p');const roles=Array.isArray(item.roles)?item.roles.length:0;meta.textContent=`${friendlyDate(item.createdAt)} · ${roles} foto${roles===1?'':'/dettagli'}`;body.append(top,title,meta);card.append(media,body);list.append(card);});}catch{count.textContent='—';verifiedCount.textContent='0';list.replaceChildren();const error=document.createElement('p');error.className='empty-state';error.textContent='Non riesco ad aprire la raccolta locale. Nessun dato è stato modificato.';list.append(error);}};
  const renderBook=async()=>{const list=byId('pendingList'),count=byId('pendingCount'),bookCount=byId('bookCount');if(!list)return;try{const observations=(await loadObservations()).filter(item=>item&&item.status==='UNKNOWN').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));count.textContent=String(observations.length);bookCount.textContent=`${observations.length} osservazioni`;list.replaceChildren();if(!observations.length){const empty=document.createElement('div');empty.className='empty-state rich-empty';empty.innerHTML='<span class="empty-leaf" aria-hidden="true">⌁</span><strong>Il primo volume aspetta la tua prima pianta.</strong><span>Ogni osservazione reale può diventare una pagina del tuo erbario.</span><a href="./observe.html">Aggiungi un’osservazione</a>';list.append(empty);return;}observations.forEach((item,index)=>{const card=document.createElement('article');card.className='book-specimen-card';const imageUrl=observationImageUrl(item);const media=document.createElement('div');media.className='book-specimen-media';if(imageUrl){const img=document.createElement('img');img.src=imageUrl;img.alt='Foto dello specimen osservato';img.loading='lazy';media.append(img);}else{const placeholder=document.createElement('div');placeholder.className='book-specimen-placeholder';placeholder.textContent='Flora Observata';media.append(placeholder);}const body=document.createElement('div');body.className='book-specimen-body';const kicker=document.createElement('span');kicker.className='book-specimen-kicker';kicker.textContent=`SPECIMEN ${String(index+1).padStart(2,'0')}`;const title=document.createElement('h3');title.textContent='Determinazione in attesa';const status=document.createElement('span');status.className='human-status pending';status.textContent='Da verificare';const meta=document.createElement('p');const roles=Array.isArray(item.roles)?item.roles.length:0;meta.textContent=`${friendlyDate(item.createdAt)} · ${roles} vista${roles===1?'':'e'} salvata${roles===1?'':'e'} localmente`;body.append(kicker,title,status,meta);card.append(media,body);list.append(card);});}catch{count.textContent='—';bookCount.textContent='Dati locali non disponibili';list.replaceChildren();const error=document.createElement('p');error.className='empty-state';error.textContent='Non riesco ad aprire il libro locale. Nessun dato è stato modificato.';list.append(error);}};
  const renderAtlas=async()=>{const locatedCount=byId('atlasLocatedCount'),regionCount=byId('atlasRegionCount'),regionsEl=byId('atlasRegions');if(!regionsEl)return;try{const observations=await loadObservations();const located=observations.filter(item=>item&&item.location&&Number.isFinite(item.location.latitude)&&Number.isFinite(item.location.longitude));const regionNames=[...new Set(observations.map(item=>typeof item.region==='string'?item.region.trim():'').filter(Boolean))].sort((a,b)=>a.localeCompare(b,'it'));locatedCount.textContent=String(located.length);regionCount.textContent=String(regionNames.length);regionsEl.replaceChildren();if(!located.length&&!regionNames.length){const empty=document.createElement('p');empty.className='empty-state';empty.textContent='Nessuna osservazione contiene ancora una posizione o una regione reale. L’atlante resta vuoto.';regionsEl.append(empty);return;}regionNames.forEach(name=>{const chip=document.createElement('span');chip.className='atlas-region-chip';chip.textContent=name;regionsEl.append(chip);});if(!regionNames.length){const note=document.createElement('p');note.className='empty-state';note.textContent=`${located.length} osservazione/i hanno coordinate locali, ma nessuna regione testuale è stata salvata.`;regionsEl.append(note);}}catch{locatedCount.textContent='—';regionCount.textContent='—';regionsEl.replaceChildren();const error=document.createElement('p');error.className='empty-state';error.textContent='Impossibile leggere l’atlante locale. Nessun dato è stato modificato.';regionsEl.append(error);}};
  const renderAcademy=async()=>{const list=byId('academyList'),count=byId('academyObservationCount'),multiCount=byId('academyMultiViewCount');if(!list)return;try{const observations=(await loadObservations()).filter(item=>item&&item.status==='UNKNOWN').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const multi=observations.filter(item=>Array.isArray(item.roles)&&item.roles.length>=2);count.textContent=String(observations.length);multiCount.textContent=String(multi.length);list.replaceChildren();if(!observations.length){const empty=document.createElement('p');empty.className='empty-state';empty.textContent='Nessuna osservazione reale disponibile. L’Academy resta vuota finché non raccogli prove sul campo.';list.append(empty);return;}observations.forEach((item,index)=>{const roles=Array.isArray(item.roles)?item.roles:[];const card=document.createElement('article');card.className='pending-card';const title=document.createElement('strong');title.textContent=`Esercizio ${String(index+1).padStart(2,'0')} · osservazione UNKNOWN`;const meta=document.createElement('span');meta.textContent=roles.length>=2?`${roles.length} viste reali · confronta forma generale e dettagli prima di qualsiasi determinazione.`:`${roles.length} vista reale · aggiungi almeno una seconda vista per documentare meglio l’esemplare.`;card.append(title,meta);list.append(card);});}catch{count.textContent='—';multiCount.textContent='—';list.replaceChildren();const error=document.createElement('p');error.className='empty-state';error.textContent='Impossibile leggere i dati locali dell’Academy. Nessun dato è stato modificato.';list.append(error);}};
  const selectedInputs=()=>inputs.filter(input=>input.files&&input.files.length);
  const setResult=(message,state='UNKNOWN')=>{if(!result)return;result.textContent=message;result.dataset.state=state;};
  const currentNegativeGate=()=>classifyNegativeEvidence(negativeSignal?negativeSignal.value:null);
  const update=()=>{if(!analyse||!result)return;const count=selectedInputs().length,gate=currentNegativeGate();analyse.disabled=count===0;if(!count){setResult('Aggiungi una foto per iniziare.','UNKNOWN');return;}setResult(gate.status==='REJECT'?'Hai indicato che la foto non mostra una pianta. Verrà conservata senza associare alcuna specie.':`Foto pronta: ${count} elemento${count===1?'':'i'} selezionato${count===1?'':'i'}. Se le prove non bastano, l’osservazione resterà da verificare.`,gate.status);};
  const fileToDataUrl=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error||new Error('Impossibile leggere la foto.'));reader.readAsDataURL(file);});
  const loadImage=dataUrl=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Impossibile decodificare la foto.'));image.src=dataUrl;});
  const canvasToBlob=canvas=>new Promise((resolve,reject)=>{canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Compressione foto fallita.')),'image/jpeg',JPEG_QUALITY);});
  const prepareEvidenceImage=async file=>{if(file.type&&!file.type.startsWith('image/'))throw new Error("Il file selezionato non è un'immagine.");if(file.size&&file.size>MAX_INPUT_BYTES)throw new Error('La foto selezionata supera il limite locale consentito.');const original=await fileToDataUrl(file),image=await loadImage(original),scale=Math.min(1,MAX_IMAGE_EDGE/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d');if(!context)throw new Error('Canvas non disponibile.');context.drawImage(image,0,0,width,height);return{blob:await canvasToBlob(canvas),width,height,originalBytes:file.size||null};};
  const validateSelection=()=>{for(const input of selectedInputs()){const file=input.files[0];if(file.type&&!file.type.startsWith('image/'))return "Il file selezionato non è un'immagine.";if(file.size&&file.size>MAX_INPUT_BYTES)return'La foto selezionata supera 12 MB: scegli una foto più leggera.';}return null;};
  if(inputs.length&&analyse&&result){inputs.forEach(input=>input.addEventListener('change',()=>{const error=validateSelection();if(error){analyse.disabled=true;setResult(`${error} Nessun dato è stato salvato.`,'UNKNOWN');return;}update();}));if(negativeSignal)negativeSignal.addEventListener('change',update);analyse.addEventListener('click',async()=>{const selected=selectedInputs();if(!selected.length)return;const selectionError=validateSelection();if(selectionError){analyse.disabled=true;setResult(`UNKNOWN — ${selectionError} Nessun dato è stato salvato.`);return;}analyse.disabled=true;setResult('Sto preparando le foto sul dispositivo…','UNKNOWN');try{const evidence=await Promise.all(selected.map(async input=>({role:input.id,name:input.files[0].name||null,type:'image/jpeg',...(await prepareEvidenceImage(input.files[0]))})));const negativeGate=currentNegativeGate();await saveObservation({id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,createdAt:new Date().toISOString(),roles:evidence.map(item=>item.role),evidence,status:negativeGate.status,negativeCategory:negativeGate.negativeCategory});setResult(negativeGate.status==='REJECT'?'Salvata come non vegetale. Nessuna specie è stata associata.':'Osservazione salvata sul dispositivo. La specie resta da verificare finché non ci sono prove sufficienti.',negativeGate.status);}catch(error){console.error(error);setResult('Non sono riuscito a salvare la foto. Nessuna osservazione incompleta è stata registrata.','UNKNOWN');}finally{const err=validateSelection();analyse.disabled=Boolean(err)||selectedInputs().length===0;}});update();}
  const network=byId('network');if(network){const setNetwork=()=>{const online=navigator.onLine;network.textContent=online?'online · dati locali':'offline · dati locali';network.setAttribute('aria-label',online?'Connessione disponibile. Le osservazioni restano memorizzate localmente.':'Senza connessione. Le funzioni locali restano disponibili.');};addEventListener('online',setNetwork);addEventListener('offline',setNetwork);setNetwork();}
  renderStats();renderCollection();renderBook();renderAtlas();renderAcademy();
})();