(() => {
  'use strict';
  const root=document.getElementById('verifiedPlates');
  const count=document.getElementById('verifiedPlateCount');
  if(!root||!count)return;
  const DB='herbarium.local.v1', STORE='observations';
  const text=(value)=>typeof value==='string'&&value.trim()?value.trim():null;
  const addField=(grid,label,value)=>{const safe=text(value);if(!safe)return;const field=document.createElement('div');field.className='plate-field';const b=document.createElement('b');b.textContent=label;const span=document.createElement('span');span.textContent=safe;field.append(b,span);grid.append(field);};
  const renderPlate=(item,index)=>{const scientific=text(item.scientificName);if(!scientific)return null;const plate=document.createElement('article');plate.className='botanical-plate';const kicker=document.createElement('p');kicker.className='plate-kicker';kicker.textContent=`Tavola ${String(index+1).padStart(2,'0')} · determinazione validata`;const title=document.createElement('h3');title.textContent=scientific;const common=document.createElement('p');common.className='plate-common';common.textContent=[text(item.commonName),text(item.family)].filter(Boolean).join(' · ')||'Nomenclatura aggiuntiva non disponibile';const grid=document.createElement('div');grid.className='plate-grid';addField(grid,'Riconoscimento',item.recognition);addField(grid,'Caratteristiche',item.characteristics);addField(grid,'Fioritura',item.flowering);addField(grid,'Esposizione',item.exposure);addField(grid,'Acqua',item.water);addField(grid,'Terreno',item.soil);addField(grid,'Moltiplicazione',item.propagation);addField(grid,'Curiosità',item.curiosity);addField(grid,'Consigli',item.careAdvice);addField(grid,'Attenzione',item.warning);plate.append(kicker,title,common,grid);return plate;};
  const load=()=>new Promise((resolve,reject)=>{if(!('indexedDB' in window))return reject(new Error('IndexedDB unavailable'));const req=indexedDB.open(DB,1);req.onsuccess=()=>{const db=req.result;const get=db.transaction(STORE,'readonly').objectStore(STORE).getAll();get.onsuccess=()=>{db.close();resolve(get.result||[])};get.onerror=()=>{db.close();reject(get.error)}};req.onerror=()=>reject(req.error)});
  load().then(items=>{const verified=items.filter(item=>item&&item.status==='VERIFIED'&&text(item.scientificName));count.textContent=String(verified.length);root.replaceChildren();if(!verified.length){const empty=document.createElement('p');empty.className='empty-state';empty.textContent='Nessuna scheda validata disponibile. Le osservazioni UNKNOWN non vengono trasformate in specie.';root.append(empty);return;}verified.forEach((item,index)=>{const plate=renderPlate(item,index);if(plate)root.append(plate);});}).catch(()=>{count.textContent='—';root.replaceChildren();const error=document.createElement('p');error.className='empty-state';error.textContent='Impossibile leggere le schede locali. Nessun dato è stato modificato.';root.append(error);});
})();