(function(){'use strict';
const TAU=Math.PI*2;
const VSH=`attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 uMVP;uniform mat4 uModel;varying vec3 vNormal;varying vec3 vWorld;void main(){vec4 w=uModel*vec4(aPosition,1.0);vWorld=w.xyz;vNormal=mat3(uModel)*aNormal;gl_Position=uMVP*vec4(aPosition,1.0);}`;
const FSH=`precision mediump float;uniform vec3 uColor;uniform vec3 uLight;uniform float uGlow;varying vec3 vNormal;varying vec3 vWorld;void main(){vec3 n=normalize(vNormal);float d=max(dot(n,normalize(uLight-vWorld)),0.0);float hemi=.36+.32*(n.y*.5+.5);float rim=pow(1.0-max(dot(n,normalize(vec3(0.0,0.2,1.0))),0.0),2.2)*.16;vec3 c=uColor*(hemi+d*.72)+vec3(uGlow+rim);gl_FragColor=vec4(c,1.0);}`;
function mat4(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])}function mul(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}function tr(x,y,z){let m=mat4();m[12]=x;m[13]=y;m[14]=z;return m}function sc(x,y,z){let m=mat4();m[0]=x;m[5]=y;m[10]=z;return m}function rx(a){let m=mat4(),c=Math.cos(a),s=Math.sin(a);m[5]=c;m[6]=s;m[9]=-s;m[10]=c;return m}function ry(a){let m=mat4(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[2]=-s;m[8]=s;m[10]=c;return m}function rz(a){let m=mat4(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[1]=s;m[4]=-s;m[5]=c;return m}function persp(fov,asp,n,f){let t=1/Math.tan(fov/2),m=new Float32Array(16);m[0]=t/asp;m[5]=t;m[10]=(f+n)/(n-f);m[11]=-1;m[14]=2*f*n/(n-f);return m}function look(eye,target,up){let z=norm(sub(eye,target)),x=norm(cross(up,z)),y=cross(z,x),m=mat4();m[0]=x[0];m[1]=y[0];m[2]=z[0];m[4]=x[1];m[5]=y[1];m[6]=z[1];m[8]=x[2];m[9]=y[2];m[10]=z[2];m[12]=-dot(x,eye);m[13]=-dot(y,eye);m[14]=-dot(z,eye);return m}function sub(a,b){return[a[0]-b[0],a[1]-b[1],a[2]-b[2]]}function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function norm(a){let l=Math.hypot(...a)||1;return a.map(v=>v/l)}
function sphere(lat=18,lon=24){let p=[],n=[],idx=[];for(let y=0;y<=lat;y++){let v=y/lat,th=v*Math.PI;for(let x=0;x<=lon;x++){let u=x/lon,ph=u*TAU,s=Math.sin(th),px=Math.cos(ph)*s,py=Math.cos(th),pz=Math.sin(ph)*s;p.push(px,py,pz);n.push(px,py,pz)}}for(let y=0;y<lat;y++)for(let x=0;x<lon;x++){let a=y*(lon+1)+x,b=a+lon+1;idx.push(a,b,a+1,b,b+1,a+1)}return{p:new Float32Array(p),n:new Float32Array(n),i:new Uint16Array(idx)}}
function cylinder(seg=18){let p=[],n=[],idx=[];for(let y=0;y<=1;y++)for(let s=0;s<=seg;s++){let a=s/seg*TAU,x=Math.cos(a),z=Math.sin(a);p.push(x,y*2-1,z);n.push(x,0,z)}for(let y=0;y<1;y++)for(let s=0;s<seg;s++){let a=y*(seg+1)+s,b=a+seg+1;idx.push(a,b,a+1,b,b+1,a+1)}return{p:new Float32Array(p),n:new Float32Array(n),i:new Uint16Array(idx)}}
function shader(gl,type,src){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}function program(gl){let p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,VSH));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,FSH));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}function mesh(gl,g){let m={count:g.i.length};m.pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,m.pb);gl.bufferData(gl.ARRAY_BUFFER,g.p,gl.STATIC_DRAW);m.nb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,m.nb);gl.bufferData(gl.ARRAY_BUFFER,g.n,gl.STATIC_DRAW);m.ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,m.ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,g.i,gl.STATIC_DRAW);return m}
const PARTS={flower:{label:'Fiore',description:'Focus dimostrativo sulla struttura fiorale. Dati scientifici dettagliati non ancora collegati.',focus:[0,1.55,0],dist:3.1},petal:{label:'Petali',description:'Petali separabili nello spazio 3D durante la vista esplosa.',focus:[.35,1.65,0],dist:2.55},head:{label:'Capolino',description:'Elemento centrale del fiore, isolabile e ruotabile nella demo.',focus:[0,1.55,.05],dist:2.25},involucre:{label:'Involucro',description:'Struttura inferiore del capolino, rappresentata come componente separato.',focus:[0,1.38,0],dist:2.45},stem:{label:'Gambo',description:'Asse verticale della pianta nella demo procedurale.',focus:[0,.45,0],dist:3.1},leaves:{label:'Foglie',description:'Foglie modellate come elementi indipendenti per focus ed esplosione.',focus:[.35,.2,0],dist:2.7},roots:{label:'Radici',description:'Apparato radicale dimostrativo, visibile sotto il terreno virtuale.',focus:[0,-1.05,0],dist:2.7},seeds:{label:'Semi',description:'Elementi dimostrativi separati nella vista esplosa; non in scala scientifica.',focus:[0,1.62,.14],dist:2.15}};
function createParts(){let a=[];const add=(name,shape,pos,scale,rot,color,explode)=>a.push({name,shape,pos,scale,rot,color,explode,base:pos.slice()});
add('stem','cyl',[0,-.05,0],[.075,.78,.075],[0,0,0],[.18,.48,.25],[0,-.45,0]);
for(let k=0;k<5;k++){let ang=-1.2+k*.62,side=k%2?1:-1;add('leaves','sph',[side*(.2+.09*k),-.25+.19*k,.02],[.42,.09,.16],[0,ang,side*.7],[.20,.50,.27],[side*.72,.12*k,-.1+.05*k])}
for(let r=0;r<7;r++){let ang=r/7*TAU,xx=Math.cos(ang)*.15,zz=Math.sin(ang)*.15;add('roots','cyl',[xx,-1.08,zz],[.025,.42,.025],[Math.cos(ang)*.55,0,-Math.sin(ang)*.55],[.28,.24,.14],[Math.cos(ang)*.55,-.45,Math.sin(ang)*.55])}
for(let k=0;k<22;k++){let ang=k/22*TAU;add('petal','sph',[Math.cos(ang)*.46,1.52,Math.sin(ang)*.46],[.16,.055,.46],[Math.PI/2,ang,0],[.93,.95,.89],[Math.cos(ang)*.62,.18,Math.sin(ang)*.62])}
add('head','sph',[0,1.56,0],[.38,.15,.38],[0,0,0],[.90,.62,.08],[0,.38,0]);
for(let k=0;k<12;k++){let ang=k/12*TAU;add('involucre','sph',[Math.cos(ang)*.30,1.40,Math.sin(ang)*.30],[.12,.05,.22],[Math.PI/2,ang,0],[.18,.40,.21],[Math.cos(ang)*.42,-.05,Math.sin(ang)*.42])}
for(let k=0;k<20;k++){let ang=k/20*TAU,rad=.12+(k%4)*.045;add('seeds','sph',[Math.cos(ang)*rad,1.66,Math.sin(ang)*rad],[.035,.045,.035],[0,0,0],[.52,.32,.08],[Math.cos(ang)*.38,.5,Math.sin(ang)*.38])}
return a}
function mount(canvas,opt={}){const gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:true});const fb=document.getElementById('fallback2d');if(!gl){canvas.style.display='none';if(fb)fb.style.display='flex';return{toggleExplode(){},reset(){},focus(){},toggleAutoRotate(){}}}const pr=program(gl),sphereMesh=mesh(gl,sphere()),cylMesh=mesh(gl,cylinder()),parts=createParts();let yaw=.42,pitch=-.12,dist=opt.mode==='home'?5.1:4.6,target=[0,.35,0],targetGoal=target.slice(),distGoal=dist,explode=0,explodeGoal=0,auto=!!opt.autoRotate,last=performance.now(),drag=false,lastPt=null,pointers=new Map(),pinchStart=null,selected='flower';
const loc={pos:gl.getAttribLocation(pr,'aPosition'),nor:gl.getAttribLocation(pr,'aNormal'),mvp:gl.getUniformLocation(pr,'uMVP'),model:gl.getUniformLocation(pr,'uModel'),color:gl.getUniformLocation(pr,'uColor'),light:gl.getUniformLocation(pr,'uLight'),glow:gl.getUniformLocation(pr,'uGlow')};gl.useProgram(pr);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.clearColor(.025,.055,.04,1);
function resize(){let d=Math.min(devicePixelRatio||1,2),w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w*d||canvas.height!==h*d){canvas.width=w*d;canvas.height=h*d;gl.viewport(0,0,canvas.width,canvas.height)}}
function modelOf(p){let ep=p.explode.map(v=>v*explode),m=tr(p.base[0]+ep[0],p.base[1]+ep[1],p.base[2]+ep[2]);m=mul(m,rz(p.rot[2]||0));m=mul(m,ry(p.rot[1]||0));m=mul(m,rx(p.rot[0]||0));m=mul(m,sc(...p.scale));let root=mul(ry(yaw),rx(pitch));return mul(root,m)}
function drawMesh(mm,m,color,viewProj){gl.bindBuffer(gl.ARRAY_BUFFER,m.pb);gl.vertexAttribPointer(loc.pos,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(loc.pos);gl.bindBuffer(gl.ARRAY_BUFFER,m.nb);gl.vertexAttribPointer(loc.nor,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(loc.nor);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,m.ib);gl.uniformMatrix4fv(loc.model,false,mm);gl.uniformMatrix4fv(loc.mvp,false,mul(viewProj,mm));gl.uniform3fv(loc.color,color);gl.uniform3f(loc.light,2.8,4.8,4.2);gl.uniform1f(loc.glow,.015);gl.drawElements(gl.TRIANGLES,m.count,gl.UNSIGNED_SHORT,0)}
function project(point){let root=mul(ry(yaw),rx(pitch)),p=[root[0]*point[0]+root[4]*point[1]+root[8]*point[2]+root[12],root[1]*point[0]+root[5]*point[1]+root[9]*point[2]+root[13],root[2]*point[0]+root[6]*point[1]+root[10]*point[2]+root[14]];let eye=[0,.15,dist],V=look(eye,target,[0,1,0]),P=persp(.72,canvas.width/canvas.height,.1,50),M=mul(P,V),x=M[0]*p[0]+M[4]*p[1]+M[8]*p[2]+M[12],y=M[1]*p[0]+M[5]*p[1]+M[9]*p[2]+M[13],w=M[3]*p[0]+M[7]*p[1]+M[11]*p[2]+M[15];return[(x/w*.5+.5)*canvas.clientWidth,(-y/w*.5+.5)*canvas.clientHeight]}
function updateHotspots(){if(!opt.hotspotRoot)return;const map={flower:[0,1.75,0],stem:[0,.4,0],leaves:[.4,.18,0],roots:[0,-1.15,0],head:[0,1.58,.05]};Object.entries(map).forEach(([name,pt])=>{let el=opt.hotspotRoot.querySelector(`[data-part="${name}"]`);if(!el)return;let s=project(pt);el.style.left=s[0]+'px';el.style.top=s[1]+'px'})}
function tick(t){resize();let dt=Math.min((t-last)/1000,.05);last=t;if(auto&&!drag)yaw+=dt*.18;explode+=(explodeGoal-explode)*Math.min(1,dt*5.5);dist+=(distGoal-dist)*Math.min(1,dt*5);for(let i=0;i<3;i++)target[i]+=(targetGoal[i]-target[i])*Math.min(1,dt*5);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);let P=persp(.72,canvas.width/canvas.height,.1,50),V=look([0,.15,dist],target,[0,1,0]),VP=mul(P,V);for(const p of parts)drawMesh(modelOf(p),p.shape==='cyl'?cylMesh:sphereMesh,p.color,VP);updateHotspots();requestAnimationFrame(tick)}
function reset(){yaw=.42;pitch=-.12;distGoal=opt.mode==='home'?5.1:4.6;targetGoal=[0,.35,0];explodeGoal=0;selected='flower';updateSelection()}function focus(name){let info=PARTS[name]||PARTS.flower;selected=name;targetGoal=info.focus.slice();distGoal=info.dist;auto=false;updateSelection();if(opt.onPart)opt.onPart(info)}function toggleExplode(){explodeGoal=explodeGoal>.5?0:1}function toggleAutoRotate(){auto=!auto}function updateSelection(){if(opt.partRail)opt.partRail.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.part===selected))}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);drag=true;lastPt=[e.clientX,e.clientY]});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);let vals=[...pointers.values()];if(vals.length===1&&lastPt){let dx=e.clientX-lastPt[0],dy=e.clientY-lastPt[1];yaw+=dx*.006;pitch=Math.max(-1.1,Math.min(.8,pitch+dy*.005));lastPt=[e.clientX,e.clientY]}else if(vals.length===2){let d=Math.hypot(vals[0][0]-vals[1][0],vals[0][1]-vals[1][1]);if(pinchStart)distGoal=Math.max(1.9,Math.min(8,distGoal+(pinchStart-d)*.008));pinchStart=d}});function end(e){pointers.delete(e.pointerId);if(!pointers.size){drag=false;lastPt=null;pinchStart=null}}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('wheel',e=>{e.preventDefault();distGoal=Math.max(1.9,Math.min(8,distGoal+e.deltaY*.003))},{passive:false});canvas.addEventListener('dblclick',()=>focus('flower'));
if(opt.partRail){['flower','petal','head','involucre','stem','leaves','roots','seeds'].forEach(name=>{let b=document.createElement('button');b.textContent=PARTS[name].label;b.dataset.part=name;b.addEventListener('click',()=>focus(name));opt.partRail.appendChild(b)})}
if(opt.hotspotRoot){['flower','stem','leaves','roots','head'].forEach(name=>{let b=document.createElement('button');b.className='hotspot';b.dataset.part=name;b.setAttribute('aria-label','Focus '+PARTS[name].label);b.innerHTML='<span>'+PARTS[name].label+'</span>';b.addEventListener('click',()=>focus(name));opt.hotspotRoot.appendChild(b)})}
if(opt.onPart)opt.onPart({label:'Pianta completa',description:'Ruota il modello, usa lo zoom oppure attiva la vista esplosa. Seleziona una parte per isolarla.'});requestAnimationFrame(tick);return{toggleExplode,reset,focus,toggleAutoRotate}}
window.Herbarium3D={mount};})();
