const JSON_HEADERS={
  'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',
  'referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=()','x-frame-options':'DENY'
};
const ALLOWED_ORIGINS=new Set(['https://webinsolito.github.io','http://localhost','http://127.0.0.1']);
const BUCKET='dealer-private-docs';
const MAX_BYTES=20*1024*1024;
const WRITE_ROLES=new Set(['ADMIN','AMMINISTRAZIONE','OPERATORE']);
const supabaseUrl=()=>Deno.env.get('SUPABASE_URL')||'';
function publishableKey(){try{const raw=Deno.env.get('SUPABASE_PUBLISHABLE_KEYS');if(raw)return JSON.parse(raw)?.default||Deno.env.get('SUPABASE_ANON_KEY')||''}catch{}return Deno.env.get('SUPABASE_ANON_KEY')||''}
const serviceKey=()=>Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
function cors(req:Request){const origin=req.headers.get('origin')||'';if(!origin)return {};const allowed=ALLOWED_ORIGINS.has(origin)||origin==='https://web.telegram.org';return allowed?{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,PUT,OPTIONS','access-control-allow-headers':'content-type,authorization,x-dealer-id','access-control-expose-headers':'content-disposition,content-length,content-type','vary':'Origin'}:{}}
const json=(data:any,status=200,extra:Record<string,string>={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}});
function serviceHeaders(extra:Record<string,string>={}){const key=serviceKey();return {apikey:key,authorization:`Bearer ${key}`,...extra}}
function publicHeaders(extra:Record<string,string>={}){return {apikey:publishableKey(),...extra}}
async function fetchJson(url:string,options:RequestInit={}){const r=await fetch(url,options),text=await r.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok){const e:any=new Error(data?.message||data?.error_description||data?.error||`http_${r.status}`);e.status=r.status;throw e}return data}
async function serviceRest(path:string,options:RequestInit={}){return fetchJson(`${supabaseUrl()}/rest/v1/${path}`,{...options,headers:{...serviceHeaders(),...(options.body?{'content-type':'application/json'}:{}),...((options.headers as Record<string,string>)||{})}})}
async function rpc(name:string,body:any){return serviceRest(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)})}
function tokenSessionId(token:string){try{const payload=token.split('.')[1];if(!payload)return null;const normalized=payload.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(payload.length/4)*4,'=');return JSON.parse(atob(normalized))?.session_id||null}catch{return null}}
async function currentUser(req:Request){const authorization=req.headers.get('authorization')||'';if(!authorization.startsWith('Bearer '))throw new Error('unauthorized');const token=authorization.slice(7),user=await fetchJson(`${supabaseUrl()}/auth/v1/user`,{headers:publicHeaders({authorization})}),sessionId=tokenSessionId(token);if(!user?.id||!sessionId)throw new Error('unauthorized');if(await rpc('security_session_active',{p_user_id:user.id,p_session_id:sessionId})!==true)throw new Error('session_revoked');return user}
async function membership(dealerId:string,userId:string){return (await serviceRest(`memberships?dealer_id=eq.${encodeURIComponent(dealerId)}&user_id=eq.${encodeURIComponent(userId)}&select=user_id,role,status,permissions&limit=1`))?.[0]||null}
function canWrite(member:any){return member?.status==='ACTIVE'&&(member?.permissions?.documents_write===true||WRITE_ROLES.has(String(member?.role||'')))}
function safeFileName(value:string){const raw=String(value||'documento').normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'_').replace(/^_+|_+$/g,'').slice(-120);return raw||'documento'}
function encodePath(path:string){return path.split('/').map(encodeURIComponent).join('/')}
function validObjectKey(key:string,dealerId:string,documentId:string){return key.startsWith(`private/${dealerId}/${documentId}/`)&&!key.includes('..')&&!key.includes('\\')}
function detectedMime(bytes:Uint8Array){
  if(bytes.length>=5&&bytes[0]===0x25&&bytes[1]===0x50&&bytes[2]===0x44&&bytes[3]===0x46&&bytes[4]===0x2d)return 'application/pdf';
  if(bytes.length>=3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return 'image/jpeg';
  if(bytes.length>=8&&[0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a].every((v,i)=>bytes[i]===v))return 'image/png';
  if(bytes.length>=12&&String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP')return 'image/webp';
  if(bytes.length>=12&&String.fromCharCode(...bytes.slice(4,8))==='ftyp'){
    const brand=String.fromCharCode(...bytes.slice(8,12));
    if(['heic','heix','hevc','hevx','mif1','msf1','heif'].includes(brand))return brand==='mif1'||brand==='msf1'?'image/heif':'image/heic';
  }
  return null;
}
async function context(req:Request,write=false){let user:any;try{user=await currentUser(req)}catch{return {response:json({ok:false,error:'unauthorized'},401,cors(req))}}const dealerId=String(req.headers.get('x-dealer-id')||'');if(!dealerId)return {response:json({ok:false,error:'dealer_required'},400,cors(req))};const member=await membership(dealerId,user.id);if(!member||member.status!=='ACTIVE')return {response:json({ok:false,error:'not_dealer_member'},403,cors(req))};if(write&&!canWrite(member))return {response:json({ok:false,error:'documents_write_required'},403,cors(req))};const url=new URL(req.url),documentId=String(url.searchParams.get('document_id')||'');if(!/^[0-9a-f-]{16,64}$/i.test(documentId))return {response:json({ok:false,error:'invalid_document_id'},400,cors(req))};const doc=(await serviceRest(`documents?dealer_id=eq.${encodeURIComponent(dealerId)}&id=eq.${encodeURIComponent(documentId)}&deleted_at=is.null&select=id,dealer_id,object_key,original_name,mime_type,size_bytes,storage_state&limit=1`))?.[0];if(!doc)return {response:json({ok:false,error:'document_not_found'},404,cors(req))};const requestedName=safeFileName(url.searchParams.get('file_name')||doc.original_name||'documento'),objectKey=validObjectKey(String(doc.object_key||''),dealerId,documentId)?String(doc.object_key):`private/${dealerId}/${documentId}/${requestedName}`;return {user,dealerId,member,documentId,doc,objectKey}}
async function upload(req:Request){const c:any=await context(req,true);if(c.response)return c.response;const length=Number(req.headers.get('content-length')||0);if(length<=0||length>MAX_BYTES)return json({ok:false,error:length>MAX_BYTES?'file_too_large':'empty_file'},length>MAX_BYTES?413:400,cors(req));const buffer=await req.arrayBuffer();if(buffer.byteLength>MAX_BYTES)return json({ok:false,error:'file_too_large'},413,cors(req));if(!buffer.byteLength)return json({ok:false,error:'empty_file'},400,cors(req));const bytes=new Uint8Array(buffer),mime=detectedMime(bytes);if(!mime)return json({ok:false,error:'file_signature_not_allowed'},415,cors(req));const declared=String(req.headers.get('content-type')||'').split(';')[0].trim().toLowerCase();if(declared&&declared!=='application/octet-stream'&&declared!==mime&&!(declared==='image/heif'&&mime==='image/heic')&&!(declared==='image/heic'&&mime==='image/heif'))return json({ok:false,error:'file_type_mismatch'},415,cors(req));const target=`${supabaseUrl()}/storage/v1/object/${BUCKET}/${encodePath(c.objectKey)}`,storageRes=await fetch(target,{method:'POST',headers:serviceHeaders({'content-type':mime,'x-upsert':'true','cache-control':'0'}),body:buffer});if(!storageRes.ok){console.error('document_upload_failed',storageRes.status);return json({ok:false,error:'storage_upload_failed'},502,cors(req))}await serviceRest(`documents?dealer_id=eq.${encodeURIComponent(c.dealerId)}&id=eq.${encodeURIComponent(c.documentId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({object_key:c.objectKey,storage_state:'CLOUD',mime_type:mime,size_bytes:buffer.byteLength,updated_at:new Date().toISOString()})});return json({ok:true,object_key:c.objectKey,size_bytes:buffer.byteLength,mime_type:mime},200,cors(req))}
async function download(req:Request){const c:any=await context(req,false);if(c.response)return c.response;if(c.doc.storage_state!=='CLOUD')return json({ok:false,error:'file_not_in_cloud'},404,cors(req));if(!validObjectKey(String(c.objectKey||''),c.dealerId,c.documentId))return json({ok:false,error:'invalid_object_key'},400,cors(req));const storageRes=await fetch(`${supabaseUrl()}/storage/v1/object/authenticated/${BUCKET}/${encodePath(c.objectKey)}`,{headers:serviceHeaders()});if(!storageRes.ok)return json({ok:false,error:'file_not_found'},storageRes.status===404?404:502,cors(req));const type=storageRes.headers.get('content-type')||c.doc.mime_type||'application/octet-stream',headers=new Headers({...JSON_HEADERS,...cors(req)});headers.set('content-type',type);headers.set('cache-control','private, no-store');headers.set('content-disposition',`inline; filename*=UTF-8''${encodeURIComponent(c.doc.original_name||'documento')}`);const len=storageRes.headers.get('content-length');if(len)headers.set('content-length',len);return new Response(storageRes.body,{status:200,headers})}
function route(req:Request){const p=new URL(req.url).pathname;return p.endsWith('/health')?'/health':p.endsWith('/file')?'/file':p}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{...JSON_HEADERS,...cors(req)}});if(!supabaseUrl()||!publishableKey()||!serviceKey())return json({ok:false,error:'backend_not_configured'},503,cors(req));try{const path=route(req);if(path==='/health'&&req.method==='GET')return json({ok:true,service:'gestionalejo-documents',version:'1.8.0',max_bytes:MAX_BYTES},200,cors(req));if(path==='/file'&&req.method==='PUT')return upload(req);if(path==='/file'&&req.method==='GET')return download(req);return json({ok:false,error:'not_found'},404,cors(req))}catch(e:any){console.error('documents_error',String(e?.message||e));return json({ok:false,error:'internal_error'},500,cors(req))}});
