// Dealer Platform Admin V1.5 — privileged tenant administration.
// This module runs only in the Cloudflare Worker. Never import it in browser code.

import {canAdministerDealer,normalizeRolePermissions,passwordPolicy,normalizeHttpsLogoUrl} from '../admin-policy.js';

const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const ROLES=new Set(['ADMIN','VENDITORE','AMMINISTRAZIONE','OPERATORE']);
const STATUSES=new Set(['INVITED','ACTIVE','SUSPENDED']);
const USERNAME_RE=/^[a-z0-9._-]{3,40}$/;
const EMAIL_RE=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;

const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}});
function cors(env,req){const origin=req.headers.get('origin')||'',appOrigin=env.APP_URL?new URL(env.APP_URL).origin:'',allowed=!origin||origin===appOrigin||origin==='https://web.telegram.org';return allowed?{'access-control-allow-origin':origin||appOrigin||'*','access-control-allow-methods':'GET,POST,PUT,OPTIONS','access-control-allow-headers':'content-type,authorization,x-dealer-id','vary':'Origin'}:{}}
function serviceHeaders(env,extra={}){return {apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,...extra}}
function publicHeaders(env,extra={}){return {apikey:env.SUPABASE_PUBLISHABLE_KEY,...extra}}
async function fetchJson(url,options={}){const r=await fetch(url,options),text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok){const err=new Error(data?.message||data?.error_description||data?.error||`http_${r.status}`);err.status=r.status;throw err}return data}
async function serviceRest(env,path,options={}){return fetchJson(`${env.SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{...serviceHeaders(env),...(options.body?{'content-type':'application/json'}:{}),...(options.headers||{})}})}
async function currentUser(env,authorization){if(!authorization?.startsWith('Bearer '))throw new Error('missing_bearer');return fetchJson(`${env.SUPABASE_URL}/auth/v1/user`,{headers:publicHeaders(env,{authorization})})}
async function membership(env,dealerId,userId){const rows=await serviceRest(env,`memberships?dealer_id=eq.${encodeURIComponent(dealerId)}&user_id=eq.${encodeURIComponent(userId)}&select=user_id,username,role,status,permissions&limit=1`);return rows?.[0]||null}
async function adminAuth(req,env,{allowMember=false}={}){let user;try{user=await currentUser(env,req.headers.get('authorization'))}catch{return {response:json({ok:false,error:'unauthorized'},401,cors(env,req))}}const dealerId=String(req.headers.get('x-dealer-id')||'');if(!dealerId)return {response:json({ok:false,error:'dealer_required'},400,cors(env,req))};const member=await membership(env,dealerId,user.id);if(!member||member.status!=='ACTIVE')return {response:json({ok:false,error:'not_dealer_member'},403,cors(env,req))};const isAdmin=canAdministerDealer(member);if(!allowMember&&!isAdmin)return {response:json({ok:false,error:'admin_required'},403,cors(env,req))};return {user,dealerId,member,isAdmin}}
function sanitizePermissions(role,value){return normalizeRolePermissions(role,value)}
function temporaryPassword(){const bytes=new Uint8Array(18);crypto.getRandomValues(bytes);const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';let out='';for(const b of bytes)out+=alphabet[b%alphabet.length];return `M23-${out}`}
async function audit(env,dealerId,actorUserId,entityType,entityId,action,beforeData=null,afterData=null){try{await serviceRest(env,'audit_logs',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({dealer_id:dealerId,actor_user_id:actorUserId,entity_type:entityType,entity_id:entityId||null,action,before_data:beforeData,after_data:afterData})})}catch(err){console.error('admin_audit_failed',err)}}
async function authAdminUser(env,userId){return fetchJson(`${env.SUPABASE_URL}/auth/v1/admin/users/${encodeURIComponent(userId)}`,{headers:serviceHeaders(env)})}
async function authCreateUser(env,email,password){return fetchJson(`${env.SUPABASE_URL}/auth/v1/admin/users`,{method:'POST',headers:serviceHeaders(env,{'content-type':'application/json'}),body:JSON.stringify({email,password,email_confirm:true})})}
async function authUpdateUser(env,userId,attributes){return fetchJson(`${env.SUPABASE_URL}/auth/v1/admin/users/${encodeURIComponent(userId)}`,{method:'PUT',headers:serviceHeaders(env,{'content-type':'application/json'}),body:JSON.stringify(attributes)})}
async function authDeleteUser(env,userId){return fetchJson(`${env.SUPABASE_URL}/auth/v1/admin/users/${encodeURIComponent(userId)}`,{method:'DELETE',headers:serviceHeaders(env)})}
async function revokeTelegram(env,dealerId,userId){await serviceRest(env,`telegram_links?dealer_id=eq.${encodeURIComponent(dealerId)}&user_id=eq.${encodeURIComponent(userId)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}})}

async function overview(req,env){const auth=await adminAuth(req,env);if(auth.response)return auth.response;const dealerRows=await serviceRest(env,`dealers?id=eq.${encodeURIComponent(auth.dealerId)}&select=id,slug,legal_name,display_name,logo_url,status,created_at,updated_at&limit=1`),dealer=dealerRows?.[0];if(!dealer)return json({ok:false,error:'dealer_not_found'},404,cors(env,req));const members=await serviceRest(env,`memberships?dealer_id=eq.${encodeURIComponent(auth.dealerId)}&select=user_id,username,role,status,permissions,created_at,updated_at&order=created_at.asc`),ids=(members||[]).map(m=>m.user_id),profiles=ids.length?await serviceRest(env,`profiles?user_id=in.(${ids.join(',')})&select=user_id,display_name,force_password_change`):[],links=await serviceRest(env,`telegram_links?dealer_id=eq.${encodeURIComponent(auth.dealerId)}&select=user_id,telegram_user_id,linked_at`),logs=await serviceRest(env,`audit_logs?dealer_id=eq.${encodeURIComponent(auth.dealerId)}&select=id,actor_user_id,entity_type,entity_id,action,created_at&order=created_at.desc&limit=20`);const profileMap=new Map((profiles||[]).map(p=>[p.user_id,p])),linkMap=new Map((links||[]).map(l=>[l.user_id,l]));const enriched=await Promise.all((members||[]).map(async m=>{let au={};try{au=await authAdminUser(env,m.user_id)}catch{}const p=profileMap.get(m.user_id)||{},l=linkMap.get(m.user_id)||null;return {...m,permissions:sanitizePermissions(m.role,m.permissions),display_name:p.display_name||m.username,force_password_change:!!p.force_password_change,email:au.email||null,last_sign_in_at:au.last_sign_in_at||null,telegram_linked:!!l,telegram_linked_at:l?.linked_at||null}}));return json({ok:true,dealer,members:enriched,audit_logs:logs||[],current_user_id:auth.user.id},200,cors(env,req))}

async function createMember(req,env){const auth=await adminAuth(req,env);if(auth.response)return auth.response;const body=await req.json().catch(()=>({})),email=String(body.email||'').trim().toLowerCase(),username=String(body.username||'').trim().toLowerCase(),displayName=String(body.display_name||'').trim(),role=String(body.role||'VENDITORE').toUpperCase();const permissions=sanitizePermissions(role,body.permissions);if(!EMAIL_RE.test(email)||!USERNAME_RE.test(username)||!displayName||displayName.length>120||!ROLES.has(role))return json({ok:false,error:'invalid_member_data'},400,cors(env,req));const duplicate=await serviceRest(env,`memberships?dealer_id=eq.${encodeURIComponent(auth.dealerId)}&username=ilike.${encodeURIComponent(username)}&select=user_id&limit=1`);if(duplicate?.length)return json({ok:false,error:'username_exists'},409,cors(env,req));const password=temporaryPassword();let created=null;try{created=await authCreateUser(env,email,password);const userId=created?.id||created?.user?.id;if(!userId)throw new Error('auth_user_missing');await serviceRest(env,'profiles?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:userId,display_name:displayName,force_password_change:true,updated_at:new Date().toISOString()})});await serviceRest(env,'memberships',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({dealer_id:auth.dealerId,user_id:userId,username,role,status:'ACTIVE',permissions})});await audit(env,auth.dealerId,auth.user.id,'membership',userId,'MEMBER_CREATED',null,{username,role,status:'ACTIVE',permissions,force_password_change:true});return json({ok:true,user_id:userId,temp_password:password},201,cors(env,req))}catch(err){const userId=created?.id||created?.user?.id;if(userId){try{await authDeleteUser(env,userId)}catch{}}const message=String(err?.message||err);return json({ok:false,error:message.includes('already')?'email_exists':'member_create_failed'},message.includes('already')?409:400,cors(env,req))}}

async function updateMember(req,env){const auth=await adminAuth(req,env);if(auth.response)return auth.response;const body=await req.json().catch(()=>({})),userId=String(body.user_id||''),role=String(body.role||'').toUpperCase(),status=String(body.status||'').toUpperCase(),displayName=String(body.display_name||'').trim();const permissions=sanitizePermissions(role,body.permissions);if(!userId||!ROLES.has(role)||!STATUSES.has(status)||displayName.length>120)return json({ok:false,error:'invalid_member_data'},400,cors(env,req));const before=await membership(env,auth.dealerId,userId);if(!before)return json({ok:false,error:'member_not_found'},404,cors(env,req));if(userId===auth.user.id&&(role!=='ADMIN'||status!=='ACTIVE'))return json({ok:false,error:'cannot_demote_or_suspend_self'},409,cors(env,req));if(before.role==='ADMIN'&&before.status==='ACTIVE'&&(role!=='ADMIN'||status!=='ACTIVE')){const admins=await serviceRest(env,`memberships?dealer_id=eq.${encodeURIComponent(auth.dealerId)}&role=eq.ADMIN&status=eq.ACTIVE&select=user_id`);if((admins||[]).length<=1)return json({ok:false,error:'last_admin_required'},409,cors(env,req))}await serviceRest(env,`memberships?dealer_id=eq.${encodeURIComponent(auth.dealerId)}&user_id=eq.${encodeURIComponent(userId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({role,status,permissions,updated_at:new Date().toISOString()})});if(displayName)await serviceRest(env,`profiles?user_id=eq.${encodeURIComponent(userId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({display_name:displayName,updated_at:new Date().toISOString()})});let telegramRevoked=false;if(status!=='ACTIVE'){await revokeTelegram(env,auth.dealerId,userId);telegramRevoked=true}await audit(env,auth.dealerId,auth.user.id,'membership',userId,'MEMBER_UPDATED',before,{role,status,permissions,display_name:displayName||undefined,telegram_revoked:telegramRevoked});return json({ok:true,permissions,telegram_revoked:telegramRevoked},200,cors(env,req))}

async function resetMemberPassword(req,env){const auth=await adminAuth(req,env);if(auth.response)return auth.response;const body=await req.json().catch(()=>({})),userId=String(body.user_id||'');if(!userId)return json({ok:false,error:'user_required'},400,cors(env,req));const target=await membership(env,auth.dealerId,userId);if(!target)return json({ok:false,error:'member_not_found'},404,cors(env,req));const password=temporaryPassword();await authUpdateUser(env,userId,{password});await serviceRest(env,`profiles?user_id=eq.${encodeURIComponent(userId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({force_password_change:true,updated_at:new Date().toISOString()})});await audit(env,auth.dealerId,auth.user.id,'membership',userId,'PASSWORD_RESET',null,{force_password_change:true});return json({ok:true,temp_password:password},200,cors(env,req))}

async function updateDealer(req,env){const auth=await adminAuth(req,env);if(auth.response)return auth.response;const body=await req.json().catch(()=>({})),displayName=String(body.display_name||'').trim(),legalName=String(body.legal_name||'').trim();let logoUrl=null;try{logoUrl=normalizeHttpsLogoUrl(body.logo_url)}catch{return json({ok:false,error:'invalid_logo_url'},400,cors(env,req))}if(!displayName||!legalName||displayName.length>120||legalName.length>180)return json({ok:false,error:'dealer_name_required'},400,cors(env,req));const before=(await serviceRest(env,`dealers?id=eq.${encodeURIComponent(auth.dealerId)}&select=id,display_name,legal_name,logo_url&limit=1`))?.[0]||null;await serviceRest(env,`dealers?id=eq.${encodeURIComponent(auth.dealerId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({display_name:displayName,legal_name:legalName,logo_url:logoUrl,updated_at:new Date().toISOString()})});await audit(env,auth.dealerId,auth.user.id,'dealer',auth.dealerId,'DEALER_UPDATED',before,{display_name:displayName,legal_name:legalName,logo_url:logoUrl});return json({ok:true},200,cors(env,req))}

async function changeOwnPassword(req,env){const auth=await adminAuth(req,env,{allowMember:true});if(auth.response)return auth.response;const body=await req.json().catch(()=>({})),password=String(body.password||'');if(!passwordPolicy(password).ok)return json({ok:false,error:'password_policy'},400,cors(env,req));await authUpdateUser(env,auth.user.id,{password});await serviceRest(env,`profiles?user_id=eq.${encodeURIComponent(auth.user.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({force_password_change:false,updated_at:new Date().toISOString()})});await audit(env,auth.dealerId,auth.user.id,'membership',auth.user.id,'PASSWORD_CHANGED',null,{force_password_change:false});return json({ok:true},200,cors(env,req))}

export async function handleAdminRoute(req,env,url){if(!url.pathname.startsWith('/admin/')&&url.pathname!=='/account/change-password')return null;if(!env.SUPABASE_URL||!env.SUPABASE_PUBLISHABLE_KEY||!env.SUPABASE_SERVICE_ROLE_KEY)return json({ok:false,error:'backend_not_configured'},503,cors(env,req));if(url.pathname==='/admin/overview'&&req.method==='GET')return overview(req,env);if(url.pathname==='/admin/member/create'&&req.method==='POST')return createMember(req,env);if(url.pathname==='/admin/member/update'&&req.method==='POST')return updateMember(req,env);if(url.pathname==='/admin/member/reset-password'&&req.method==='POST')return resetMemberPassword(req,env);if(url.pathname==='/admin/dealer/update'&&req.method==='POST')return updateDealer(req,env);if(url.pathname==='/account/change-password'&&req.method==='POST')return changeOwnPassword(req,env);return json({ok:false,error:'not_found'},404,cors(env,req))}
