const APP='https://webinsolito.github.io/webinsolito/dealer-platform/';
const JSON_HEADERS={
  'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',
  'referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=()','x-frame-options':'DENY'
};
const ALLOWED_ORIGINS=new Set(['https://webinsolito.github.io','https://web.telegram.org','http://localhost','http://127.0.0.1']);
const supabaseUrl=()=>Deno.env.get('SUPABASE_URL')||'';
const serviceKey=()=>Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
function publishableKey(){try{const raw=Deno.env.get('SUPABASE_PUBLISHABLE_KEYS');if(raw)return JSON.parse(raw)?.default||Deno.env.get('SUPABASE_ANON_KEY')||''}catch{}return Deno.env.get('SUPABASE_ANON_KEY')||''}
function cors(req:Request){const origin=req.headers.get('origin')||'';if(!origin)return {};return ALLOWED_ORIGINS.has(origin)?{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization,x-dealer-id,x-telegram-bot-api-secret-token','vary':'Origin'}:{}}
const json=(data:any,status=200,extra:Record<string,string>={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}});
async function readJson(req:Request,max:number){const length=Number(req.headers.get('content-length')||0);if(length>max)throw Object.assign(new Error('payload_too_large'),{status:413});const text=await req.text();if(new TextEncoder().encode(text).byteLength>max)throw Object.assign(new Error('payload_too_large'),{status:413});if(!text)return {};try{return JSON.parse(text)}catch{throw Object.assign(new Error('invalid_json'),{status:400})}}
function serviceHeaders(extra:Record<string,string>={}){const key=serviceKey();return {apikey:key,authorization:`Bearer ${key}`,...extra}}
function publicHeaders(extra:Record<string,string>={}){return {apikey:publishableKey(),...extra}}
async function fetchJson(url:string,options:RequestInit={}){const res=await fetch(url,options),text=await res.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!res.ok){const e:any=new Error(data?.description||data?.message||data?.error_description||data?.error||`http_${res.status}`);e.status=res.status;throw e}return data}
async function serviceRest(path:string,options:RequestInit={}){return fetchJson(`${supabaseUrl()}/rest/v1/${path}`,{...options,headers:{...serviceHeaders(),...(options.body?{'content-type':'application/json'}:{}),...((options.headers as Record<string,string>)||{})}})}
async function rpc(name:string,body:any){return serviceRest(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)})}
async function runtimeConfig(){return (await serviceRest('rpc/telegram_runtime_config',{method:'POST',body:'{}'}))||{}}
function tokenSessionId(token:string){try{const payload=token.split('.')[1];if(!payload)return null;const normalized=payload.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(payload.length/4)*4,'=');return JSON.parse(atob(normalized))?.session_id||null}catch{return null}}
async function currentUser(req:Request){const authorization=req.headers.get('authorization')||'';if(!authorization.startsWith('Bearer '))throw new Error('unauthorized');const token=authorization.slice(7),user=await fetchJson(`${supabaseUrl()}/auth/v1/user`,{headers:publicHeaders({authorization})}),sessionId=tokenSessionId(token);if(!user?.id||!sessionId)throw new Error('unauthorized');if(await rpc('security_session_active',{p_user_id:user.id,p_session_id:sessionId})!==true)throw new Error('session_revoked');return user}
async function activeMembership(dealerId:string,userId:string){return (await serviceRest(`memberships?dealer_id=eq.${encodeURIComponent(dealerId)}&user_id=eq.${encodeURIComponent(userId)}&status=eq.ACTIVE&select=user_id,role,permissions&limit=1`))?.[0]||null}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
async function hmac(key:Uint8Array,data:string){const cryptoKey=await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',cryptoKey,new TextEncoder().encode(data)))}
const hex=(bytes:Uint8Array)=>[...bytes].map(b=>b.toString(16).padStart(2,'0')).join('');
async function validateInitData(initData:string,botToken:string){if(!initData||initData.length>8192||!botToken)return {ok:false,reason:'missing_or_oversized_data'};const params=new URLSearchParams(initData),received=params.get('hash')||'';if(!/^[0-9a-f]{64}$/i.test(received))return {ok:false,reason:'invalid_hash'};params.delete('hash');const authDate=Number(params.get('auth_date')||0),now=Math.floor(Date.now()/1000);if(!authDate||Math.abs(now-authDate)>600)return {ok:false,reason:'expired'};const check=[...params.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n'),secret=await hmac(new TextEncoder().encode('WebAppData'),botToken),computed=hex(await hmac(secret,check));if(!safeEqual(computed,received.toLowerCase()))return {ok:false,reason:'invalid_hash'};let user:any=null;try{user=JSON.parse(params.get('user')||'null')}catch{}return user?.id?{ok:true,user:{id:user.id,first_name:user.first_name||null,username:user.username||null},authDate}:{ok:false,reason:'missing_user'}}
async function telegram(token:string,method:string,payload:any){return fetchJson(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)})}
async function linkTelegram(req:Request){const runtime=await runtimeConfig();if(!runtime.bot_token)return json({ok:false,error:'telegram_not_configured'},503,cors(req));let user:any;try{user=await currentUser(req)}catch{return json({ok:false,error:'unauthorized'},401,cors(req))}const body=await readJson(req,16384),valid:any=await validateInitData(String(body.initData||''),runtime.bot_token);if(!valid.ok)return json(valid,401,cors(req));const dealerId=String(body.dealer_id||req.headers.get('x-dealer-id')||'');if(!dealerId)return json({ok:false,error:'dealer_required'},400,cors(req));if(!await activeMembership(dealerId,user.id))return json({ok:false,error:'not_dealer_member'},403,cors(req));try{await serviceRest('telegram_links?on_conflict=dealer_id,user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({dealer_id:dealerId,user_id:user.id,telegram_user_id:String(valid.user.id),linked_at:new Date().toISOString()})})}catch{return json({ok:false,error:'telegram_link_conflict'},409,cors(req))}return json({ok:true,telegram_user:valid.user},200,cors(req))}
async function telegramLinks(telegramUserId:string){const rows=await serviceRest(`telegram_links?telegram_user_id=eq.${encodeURIComponent(telegramUserId)}&select=dealer_id,user_id`),result:any[]=[];for(const link of rows||[]){const member=await activeMembership(link.dealer_id,link.user_id);if(!member)continue;const dealer=(await serviceRest(`dealers?id=eq.${link.dealer_id}&status=eq.ACTIVE&select=id,slug,display_name&limit=1`))?.[0];if(dealer)result.push({...link,dealer,member})}return result}
function canSeeFinance(member:any){return ['ADMIN','AMMINISTRAZIONE'].includes(String(member?.role||''))&&member?.permissions?.finance_view!==false&&member?.permissions?.view_costs!==false}
function canSeeInvoices(member:any){return ['ADMIN','AMMINISTRAZIONE'].includes(String(member?.role||''))&&member?.permissions?.invoices_view!==false}
async function dealerContext(link:any){
  const dealer=link.dealer,finance=canSeeFinance(link.member),invoiceAccess=canSeeInvoices(link.member);
  const [vehicles,financials,customers,workItems,calendarEvents,invoices]=await Promise.all([
    serviceRest(`vehicles?dealer_id=eq.${dealer.id}&deleted_at=is.null&select=id,status,created_at`),
    finance?serviceRest(`vehicle_financials?dealer_id=eq.${dealer.id}&select=vehicle_id,purchase_date`):Promise.resolve([]),
    serviceRest(`customers?dealer_id=eq.${dealer.id}&deleted_at=is.null&select=id,next_contact_at`),
    serviceRest(`vehicle_work_items?dealer_id=eq.${dealer.id}&status=neq.DONE&status=neq.CANCELLED&select=id`),
    serviceRest(`calendar_events?dealer_id=eq.${dealer.id}&status=neq.CANCELLED&select=id,starts_at`),
    invoiceAccess?serviceRest(`invoices?dealer_id=eq.${dealer.id}&deleted_at=is.null&select=id,invoice_type,total_amount,paid_amount,due_date,payment_status`):Promise.resolve([])
  ]);
  const purchaseDateByVehicle=new Map((financials||[]).map((x:any)=>[x.vehicle_id,x.purchase_date])),now=Date.now(),tomorrow=now+86400000,today=new Date().toISOString().slice(0,10),saleInvoices=(invoices||[]).filter((x:any)=>x.invoice_type==='SALE'&&x.payment_status!=='PAID'&&Number(x.total_amount||0)>Number(x.paid_amount||0));
  const oldStock=(vehicles||[]).filter((x:any)=>{if(['VENDUTA','DA_CONSEGNARE','CONSEGNATA'].includes(x.status))return false;const stockDate=purchaseDateByVehicle.get(x.id)||x.created_at;return !!stockDate&&Math.floor((now-new Date(String(stockDate)).getTime())/86400000)>=60}).length;
  return {dealer,member:link.member,vehicleCount:vehicles?.length||0,callbacks:(customers||[]).filter((x:any)=>x.next_contact_at&&new Date(x.next_contact_at).getTime()<=tomorrow).length,deliveries:(vehicles||[]).filter((x:any)=>x.status==='DA_CONSEGNARE').length,openWorks:workItems?.length||0,appointments:(calendarEvents||[]).filter((x:any)=>String(x.starts_at||'').slice(0,10)===today).length,receivables:invoiceAccess?saleInvoices.reduce((sum:number,x:any)=>sum+Math.max(0,Number(x.total_amount||0)-Number(x.paid_amount||0)),0):null,overdueInvoices:invoiceAccess?saleInvoices.filter((x:any)=>x.due_date&&String(x.due_date).slice(0,10)<today).length:null,oldStock};
}
function appUrl(slug:string,view:string){const url=new URL(APP);url.searchParams.set('dealer',slug);url.searchParams.set('view',view);url.searchParams.set('v','1.8.0');return url.toString()}
const euro=(value:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value||0);
function dashboardText(ctx:any){const tasks:string[]=[];if(ctx.callbacks>0)tasks.push(`📞 ${ctx.callbacks} ${ctx.callbacks===1?'richiamo':'richiami'} entro domani`);if(ctx.appointments>0)tasks.push(`📅 ${ctx.appointments} ${ctx.appointments===1?'appuntamento':'appuntamenti'} oggi`);if(ctx.deliveries>0)tasks.push(`🚚 ${ctx.deliveries} ${ctx.deliveries===1?'consegna':'consegne'} da preparare`);if(ctx.openWorks>0)tasks.push(`🔧 ${ctx.openWorks} ${ctx.openWorks===1?'lavoro aperto':'lavori aperti'}`);if(ctx.receivables!==null&&ctx.receivables>0)tasks.push(`💶 ${euro(ctx.receivables)} da incassare`);if(ctx.overdueInvoices!==null&&ctx.overdueInvoices>0)tasks.push(`⚠️ ${ctx.overdueInvoices} ${ctx.overdueInvoices===1?'fattura scaduta':'fatture scadute'}`);if(ctx.oldStock>0)tasks.push(`⏳ ${ctx.oldStock} ${ctx.oldStock===1?'auto ferma':'auto ferme'} da oltre 60 giorni`);const status=tasks.length?`OGGI\n${tasks.join('\n')}`:'✅ TUTTO SOTTO CONTROLLO\nNessuna attività urgente per oggi.';return `${ctx.dealer.display_name}\n\nCiao 👋\n\n${status}${ctx.vehicleCount?`\n\n🚗 ${ctx.vehicleCount} auto in stock`:''}`}
function dashboardKeyboard(ctx:any){const slug=ctx.dealer.slug,id=ctx.dealer.id;return {inline_keyboard:[[{text:'🚀 APRI GESTIONALE',web_app:{url:appUrl(slug,'today')}}],[{text:'☀️ OGGI',web_app:{url:appUrl(slug,'today')}},{text:'↻ AGGIORNA',callback_data:`dealer:status:${id}`}]]}}
async function showDashboard(token:string,chatId:any,ctx:any,messageId?:number){const payload:any={chat_id:chatId,text:dashboardText(ctx),reply_markup:dashboardKeyboard(ctx)};if(messageId){payload.message_id=messageId;try{return await telegram(token,'editMessageText',payload)}catch(err:any){if(String(err).includes('message is not modified'))return;throw err}}return telegram(token,'sendMessage',payload)}
async function showSelector(token:string,chatId:any,links:any[],messageId?:number){const payload:any={chat_id:chatId,text:'Scegli la concessionaria:',reply_markup:{inline_keyboard:links.slice(0,10).map(link=>[{text:`🏢 ${link.dealer.display_name}`,callback_data:`dealer:select:${link.dealer.id}`}])}};if(messageId){payload.message_id=messageId;return telegram(token,'editMessageText',payload)}return telegram(token,'sendMessage',payload)}
async function showReserved(token:string,chatId:any){return telegram(token,'sendMessage',{chat_id:chatId,text:'🔒 ACCESSO RISERVATO\n\nApri GestionaleJo e collega il tuo account Telegram.',reply_markup:{inline_keyboard:[[{text:'🚀 APRI GESTIONALE',web_app:{url:APP}}]]}})}
async function webhook(req:Request){const runtime=await runtimeConfig();if(!runtime.bot_token||!runtime.webhook_secret)return json({ok:false,error:'telegram_not_configured'},503);if(!safeEqual(req.headers.get('x-telegram-bot-api-secret-token')||'',String(runtime.webhook_secret)))return json({ok:false,error:'forbidden'},403);const update=await readJson(req,1024*1024),callback=update.callback_query,message=update.message||callback?.message,chatId=message?.chat?.id,from=update.message?.from||callback?.from;if(!chatId||!from?.id)return json({ok:true,ignored:true});const links=await telegramLinks(String(from.id));if(callback){const data=String(callback.data||'');if(data.startsWith('dealer:select:')||data.startsWith('dealer:status:')){const dealerId=data.split(':').slice(2).join(':'),link=links.find(x=>x.dealer.id===dealerId);if(!link){await telegram(runtime.bot_token,'answerCallbackQuery',{callback_query_id:callback.id,text:'Accesso non disponibile.',show_alert:true});return json({ok:true})}await telegram(runtime.bot_token,'answerCallbackQuery',{callback_query_id:callback.id,text:data.startsWith('dealer:status:')?'Aggiornato':'Concessionaria selezionata'});await showDashboard(runtime.bot_token,chatId,await dealerContext(link),message.message_id);return json({ok:true})}await telegram(runtime.bot_token,'answerCallbackQuery',{callback_query_id:callback.id,text:'Azione non disponibile'});return json({ok:true})}const text=String(update.message?.text||'').trim();if(['/start','/menu','/status'].some(cmd=>text===cmd||text.startsWith(`${cmd} `))){const preferred=text.startsWith('/start ')?text.slice(7).trim():'',link=preferred?links.find(x=>x.dealer.id===preferred||x.dealer.slug===preferred):null;if(!links.length)await showReserved(runtime.bot_token,chatId);else if(link||links.length===1)await showDashboard(runtime.bot_token,chatId,await dealerContext(link||links[0]));else await showSelector(runtime.bot_token,chatId,links)}else if(text.startsWith('/'))await telegram(runtime.bot_token,'sendMessage',{chat_id:chatId,text:'Usa /menu per aprire GestionaleJo.'});return json({ok:true})}
function route(req:Request){const pathname=new URL(req.url).pathname;for(const p of ['/health','/validate','/link','/webhook'])if(pathname===p||pathname.endsWith(p))return p;return pathname}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{...JSON_HEADERS,...cors(req)}});if(!supabaseUrl()||!publishableKey()||!serviceKey())return json({ok:false,error:'backend_not_configured'},503,cors(req));try{const path=route(req);if(path==='/health'&&req.method==='GET'){const runtime=await runtimeConfig();return json({ok:true,service:'gestionalejo-telegram',version:'1.8.0',botConfigured:!!runtime.bot_token,webhookReady:!!runtime.bot_token&&!!runtime.webhook_secret},200,cors(req))}if(path==='/validate'&&req.method==='POST'){const runtime=await runtimeConfig();if(!runtime.bot_token)return json({ok:false,error:'telegram_not_configured'},503,cors(req));const body=await readJson(req,16384),result:any=await validateInitData(String(body.initData||''),runtime.bot_token);return json(result,result.ok?200:401,cors(req))}if(path==='/link'&&req.method==='POST')return linkTelegram(req);if(path==='/webhook'&&req.method==='POST')return webhook(req);return json({ok:false,error:'not_found'},404,cors(req))}catch(err:any){const status=Number(err?.status)||500;console.error('telegram_error',String(err?.message||err));return json({ok:false,error:status===413?'payload_too_large':status===400?'invalid_request':'internal_error'},status>=400&&status<600?status:500,cors(req))}});
