const APP='https://webinsolito.github.io/webinsolito/dealer-platform/';
const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const supabaseUrl=()=>Deno.env.get('SUPABASE_URL')||'';
const serviceKey=()=>Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
function publishableKey(){try{const raw=Deno.env.get('SUPABASE_PUBLISHABLE_KEYS');if(raw)return JSON.parse(raw)?.default||Deno.env.get('SUPABASE_ANON_KEY')||''}catch{}return Deno.env.get('SUPABASE_ANON_KEY')||''}
const json=(data:any,status=200,extra:Record<string,string>={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}});
function cors(req:Request){const origin=req.headers.get('origin')||'',allowed=!origin||origin==='https://webinsolito.github.io'||origin==='https://web.telegram.org'||origin.startsWith('http://localhost')||origin.startsWith('http://127.0.0.1');return allowed?{'access-control-allow-origin':origin||'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization,x-dealer-id,x-telegram-bot-api-secret-token','vary':'Origin'}:{}}
function serviceHeaders(extra:Record<string,string>={}){const key=serviceKey();return {apikey:key,authorization:`Bearer ${key}`,...extra}}
function publicHeaders(extra:Record<string,string>={}){return {apikey:publishableKey(),...extra}}
async function fetchJson(url:string,options:RequestInit={}){const res=await fetch(url,options),text=await res.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!res.ok)throw new Error(data?.description||data?.message||data?.error_description||data?.error||`http_${res.status}`);return data}
async function serviceRest(path:string,options:RequestInit={}){return fetchJson(`${supabaseUrl()}/rest/v1/${path}`,{...options,headers:{...serviceHeaders(),...(options.body?{'content-type':'application/json'}:{}),...((options.headers as Record<string,string>)||{})}})}
async function runtimeConfig(){return (await serviceRest('rpc/telegram_runtime_config',{method:'POST',body:'{}'}))||{}}
async function currentUser(req:Request){const authorization=req.headers.get('authorization')||'';if(!authorization.startsWith('Bearer '))throw new Error('unauthorized');return fetchJson(`${supabaseUrl()}/auth/v1/user`,{headers:publicHeaders({authorization})})}
async function activeMembership(dealerId:string,userId:string){return (await serviceRest(`memberships?dealer_id=eq.${encodeURIComponent(dealerId)}&user_id=eq.${encodeURIComponent(userId)}&status=eq.ACTIVE&select=user_id,role,permissions&limit=1`))?.[0]||null}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
async function hmac(key:Uint8Array,data:string){const cryptoKey=await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',cryptoKey,new TextEncoder().encode(data)))}
const hex=(bytes:Uint8Array)=>[...bytes].map(b=>b.toString(16).padStart(2,'0')).join('');
async function validateInitData(initData:string,botToken:string){if(!initData||!botToken)return {ok:false,reason:'missing_data'};const params=new URLSearchParams(initData),received=params.get('hash')||'';if(!received)return {ok:false,reason:'missing_hash'};params.delete('hash');const authDate=Number(params.get('auth_date')||0),now=Math.floor(Date.now()/1000);if(!authDate||Math.abs(now-authDate)>900)return {ok:false,reason:'expired'};const check=[...params.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n'),secret=await hmac(new TextEncoder().encode('WebAppData'),botToken),computed=hex(await hmac(secret,check));if(!safeEqual(computed,received))return {ok:false,reason:'invalid_hash'};let user:any=null;try{user=JSON.parse(params.get('user')||'null')}catch{}return user?.id?{ok:true,user,authDate}:{ok:false,reason:'missing_user'}}
async function telegram(token:string,method:string,payload:any){return fetchJson(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)})}
async function linkTelegram(req:Request){const runtime=await runtimeConfig();if(!runtime.bot_token)return json({ok:false,error:'telegram_not_configured'},503,cors(req));let user:any;try{user=await currentUser(req)}catch{return json({ok:false,error:'unauthorized'},401,cors(req))}const body=await req.json().catch(()=>({})),valid:any=await validateInitData(String(body.initData||''),runtime.bot_token);if(!valid.ok)return json(valid,401,cors(req));const dealerId=String(body.dealer_id||req.headers.get('x-dealer-id')||'');if(!dealerId)return json({ok:false,error:'dealer_required'},400,cors(req));if(!await activeMembership(dealerId,user.id))return json({ok:false,error:'not_dealer_member'},403,cors(req));try{await serviceRest('telegram_links?on_conflict=dealer_id,user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({dealer_id:dealerId,user_id:user.id,telegram_user_id:String(valid.user.id),linked_at:new Date().toISOString()})})}catch(err:any){return json({ok:false,error:String(err).includes('telegram_user_id')?'telegram_already_linked':'telegram_link_failed'},409,cors(req))}return json({ok:true,telegram_user:{id:valid.user.id,first_name:valid.user.first_name||null,username:valid.user.username||null}},200,cors(req))}
async function telegramLinks(telegramUserId:string){const rows=await serviceRest(`telegram_links?telegram_user_id=eq.${encodeURIComponent(telegramUserId)}&select=dealer_id,user_id`),result:any[]=[];for(const link of rows||[]){if(!await activeMembership(link.dealer_id,link.user_id))continue;const dealer=(await serviceRest(`dealers?id=eq.${link.dealer_id}&status=eq.ACTIVE&select=id,slug,display_name&limit=1`))?.[0];if(dealer)result.push({...link,dealer})}return result}
async function dealerContext(link:any){const dealer=link.dealer,profile=(await serviceRest(`profiles?user_id=eq.${link.user_id}&select=display_name&limit=1`))?.[0]||{},[vehicles,customers,workItems,calendarEvents,invoices]=await Promise.all([serviceRest(`vehicles?dealer_id=eq.${dealer.id}&deleted_at=is.null&select=id,status,purchase_date,created_at`),serviceRest(`customers?dealer_id=eq.${dealer.id}&deleted_at=is.null&select=id,next_contact_at`),serviceRest(`vehicle_work_items?dealer_id=eq.${dealer.id}&status=neq.DONE&status=neq.CANCELLED&select=id`),serviceRest(`calendar_events?dealer_id=eq.${dealer.id}&status=neq.CANCELLED&select=id,starts_at`),serviceRest(`invoices?dealer_id=eq.${dealer.id}&deleted_at=is.null&select=id,invoice_type,total_amount,paid_amount,due_date,payment_status`)]),now=Date.now(),tomorrow=now+86400000,today=new Date().toISOString().slice(0,10),saleInvoices=(invoices||[]).filter((x:any)=>x.invoice_type==='SALE'&&x.payment_status!=='PAID'&&Number(x.total_amount||0)>Number(x.paid_amount||0));return {dealer,profile,vehicleCount:vehicles?.length||0,callbacks:(customers||[]).filter((x:any)=>x.next_contact_at&&new Date(x.next_contact_at).getTime()<=tomorrow).length,deliveries:(vehicles||[]).filter((x:any)=>x.status==='DA_CONSEGNARE').length,openWorks:workItems?.length||0,appointments:(calendarEvents||[]).filter((x:any)=>String(x.starts_at||'').slice(0,10)===today).length,receivables:saleInvoices.reduce((sum:number,x:any)=>sum+Math.max(0,Number(x.total_amount||0)-Number(x.paid_amount||0)),0),overdueInvoices:saleInvoices.filter((x:any)=>x.due_date&&String(x.due_date).slice(0,10)<today).length,oldStock:(vehicles||[]).filter((x:any)=>!['VENDUTA','DA_CONSEGNARE','CONSEGNATA'].includes(x.status)&&(x.purchase_date||x.created_at)&&Math.floor((now-new Date(x.purchase_date||x.created_at).getTime())/86400000)>=60).length}}
function appUrl(slug:string,view:string){const url=new URL(APP);url.searchParams.set('dealer',slug);url.searchParams.set('view',view);url.searchParams.set('v','1.7.2');return url.toString()}
function dashboardText(ctx:any,name=''){const due=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(ctx.receivables||0);return `${ctx.dealer.display_name}\n\nCiao ${ctx.profile?.display_name||name||'utente'} 👋\n\nOGGI\n📞 ${ctx.callbacks} richiami entro domani\n📅 ${ctx.appointments} appuntamenti oggi\n🚚 ${ctx.deliveries} consegne da preparare\n🔧 ${ctx.openWorks} lavori aperti\n💶 ${due} da incassare${ctx.overdueInvoices?` · ${ctx.overdueInvoices} scadute`:''}\n\n🚗 ${ctx.vehicleCount} auto nel Garage${ctx.oldStock?`\n⏳ ${ctx.oldStock} auto oltre 60 giorni`:''}`}
function dashboardKeyboard(ctx:any){const slug=ctx.dealer.slug,id=ctx.dealer.id;return {inline_keyboard:[[{text:'APRI OGGI',web_app:{url:appUrl(slug,'today')}}],[{text:'🚗 Garage',web_app:{url:appUrl(slug,'garage')}},{text:'👥 Clienti',web_app:{url:appUrl(slug,'clients')}}],[{text:'🤝 Vendite',web_app:{url:appUrl(slug,'vendite')}},{text:'🧾 Fatture',web_app:{url:appUrl(slug,'fatture')}}],[{text:'📅 Calendario',web_app:{url:appUrl(slug,'calendar')}},{text:'📄 Documenti',web_app:{url:appUrl(slug,'documenti')}}],[{text:'◉ AutoScout',web_app:{url:appUrl(slug,'autoscout')}},{text:'📊 Finanze',web_app:{url:appUrl(slug,'finanze')}}],[{text:'↻ Aggiorna',callback_data:`dealer:status:${id}`}]]}}
async function showDashboard(token:string,chatId:any,from:any,ctx:any,messageId?:number){const payload:any={chat_id:chatId,text:dashboardText(ctx,from?.first_name),reply_markup:dashboardKeyboard(ctx)};if(messageId){payload.message_id=messageId;try{return await telegram(token,'editMessageText',payload)}catch(err:any){if(String(err).includes('message is not modified'))return;throw err}}return telegram(token,'sendMessage',payload)}
async function showSelector(token:string,chatId:any,links:any[],messageId?:number){const payload:any={chat_id:chatId,text:'Scegli la concessionaria da aprire:',reply_markup:{inline_keyboard:links.slice(0,10).map(link=>[{text:`🏢 ${link.dealer.display_name}`,callback_data:`dealer:select:${link.dealer.id}`}])}};if(messageId){payload.message_id=messageId;return telegram(token,'editMessageText',payload)}return telegram(token,'sendMessage',payload)}
async function showReserved(token:string,chatId:any){return telegram(token,'sendMessage',{chat_id:chatId,text:'🔒 ACCESSO RISERVATO\n\nAccedi alla Mini App e collega il tuo account Telegram.',reply_markup:{inline_keyboard:[[{text:'ACCEDI',web_app:{url:APP}}]]}})}
async function webhook(req:Request){const runtime=await runtimeConfig();if(!runtime.bot_token||!runtime.webhook_secret)return json({ok:false,error:'telegram_not_configured'},503);if(!safeEqual(req.headers.get('x-telegram-bot-api-secret-token')||'',String(runtime.webhook_secret)))return json({ok:false,error:'forbidden'},403);const update=await req.json().catch(()=>({})),callback=update.callback_query,message=update.message||callback?.message,chatId=message?.chat?.id,from=update.message?.from||callback?.from;if(!chatId||!from?.id)return json({ok:true,ignored:true});const links=await telegramLinks(String(from.id));if(callback){const data=String(callback.data||'');if(data.startsWith('dealer:select:')||data.startsWith('dealer:status:')){const dealerId=data.split(':').slice(2).join(':'),link=links.find(x=>x.dealer.id===dealerId);if(!link){await telegram(runtime.bot_token,'answerCallbackQuery',{callback_query_id:callback.id,text:'Accesso non disponibile.',show_alert:true});return json({ok:true})}await telegram(runtime.bot_token,'answerCallbackQuery',{callback_query_id:callback.id,text:data.startsWith('dealer:status:')?'Stato aggiornato':'Concessionaria selezionata'});await showDashboard(runtime.bot_token,chatId,from,await dealerContext(link),message.message_id);return json({ok:true})}await telegram(runtime.bot_token,'answerCallbackQuery',{callback_query_id:callback.id,text:'Azione non disponibile'});return json({ok:true})}const text=String(update.message?.text||'').trim();if(['/start','/menu','/status'].some(cmd=>text===cmd||text.startsWith(`${cmd} `))){const preferred=text.startsWith('/start ')?text.slice(7).trim():'',link=preferred?links.find(x=>x.dealer.id===preferred||x.dealer.slug===preferred):null;if(!links.length)await showReserved(runtime.bot_token,chatId);else if(link||links.length===1)await showDashboard(runtime.bot_token,chatId,from,await dealerContext(link||links[0]));else await showSelector(runtime.bot_token,chatId,links)}else if(text.startsWith('/'))await telegram(runtime.bot_token,'sendMessage',{chat_id:chatId,text:'Comando non riconosciuto. Usa /menu per aprire GestionaleJo.'});return json({ok:true})}
function route(req:Request){const pathname=new URL(req.url).pathname;for(const p of ['/health','/validate','/link','/webhook'])if(pathname===p||pathname.endsWith(p))return p;return pathname}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(!supabaseUrl()||!publishableKey()||!serviceKey())return json({ok:false,error:'backend_not_configured'},503,cors(req));try{const path=route(req);if(path==='/health'){const runtime=await runtimeConfig();return json({ok:true,service:'gestionalejo-telegram',version:'1.7.2',botConfigured:!!runtime.bot_token,webhookSecretConfigured:!!runtime.webhook_secret,webhookReady:!!runtime.bot_token&&!!runtime.webhook_secret},200,cors(req))}if(path==='/validate'&&req.method==='POST'){const runtime=await runtimeConfig();if(!runtime.bot_token)return json({ok:false,error:'telegram_not_configured'},503,cors(req));const body=await req.json().catch(()=>({})),result:any=await validateInitData(String(body.initData||''),runtime.bot_token);return json(result,result.ok?200:401,cors(req))}if(path==='/link'&&req.method==='POST')return linkTelegram(req);if(path==='/webhook'&&req.method==='POST')return webhook(req);return json({ok:false,error:'not_found'},404,cors(req))}catch(err:any){console.error('telegram_error',String(err?.message||err));return json({ok:false,error:'internal_error'},500,cors(req))}});
